## <span style="color:purple">Morphological analysis with Bert based disambiguation</span>

In addition to the default morphological analysis, which is provided by the VabamorfTagger, the estnltk_neural package contains VabamorfWithBertTagger, which provides Vabamorf's morphological analysis completed by _Bert based morphological disambiguation_. 
The latter is often more accurate than Vabamorf's morphological disambiguation.

VabamorfWithBertTagger uses 

1. VabamorfAnalyzer (for morph_analysis layer) 
2. PostMorphAnalysisTagger (corrections) 
3. BertMorphTagger (as a disambiguator)

## Examples how to use VabamorfWithBertTagger

In [1]:
from estnltk import Text
from estnltk_neural.taggers import VabamorfWithBertTagger

C:\Programmid\Miniconda3\envs\py313_devel\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### VabamorfWithBertTagger without verb corrections

correct_verb_annotation and change_to_bert_form flags determine if verbs are updated based on BertMorpTagger analysis. By default, both flags are set to True.

When there is no verb multiplicity, then for 91% of the time (1789/1945 cases on UD treebank 2.18), the Bert's verb analysis improves the Vabamorf analysis. This is mostly because of "neg" in Bert's form analysis.

In [2]:
vbt = VabamorfWithBertTagger(use_postanalysis=True,
                             correct_verb_annotation=False,
                             change_to_bert_form=False)

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 361.44it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

In [4]:
txt1 = Text("Meie ei pea otsima.")
txt1.tag_layer(["words", "sentences"])

vbt.tag( txt1 )
txt1["morph_analysis"]

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Meie', [{'normalized_text': 'Meie', 'lemma': 'mina', 'root': 'mina', 'root_tokens': ['mina'], 'ending': '0', 'clitic': '', 'form': 'pl n', 'partofspeech': 'P'}]),
Span('ei', [{'normalized_text': 'ei', 'lemma': 'ei', 'root': 'ei', 'root_tokens': ['ei'], 'ending': '0', 'clitic': '', 'form': 'neg', 'partofspeech': 'V'}]),
Span('pea', [{'normalized_text': 'pea', 'lemma': 'pea', 'root': 'pea', 'root_tokens': ['pea'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'D'}, {'normalized_text': 'pea', 'lemma': 'pea', 'root': 'pea', 'root_tokens': ['pea'], 'ending': '0', 'clitic': '', 'form': 'sg g', 'partofspeech': 'S'}, {'normalized_text': 'pea', 'lemma': 'pidama', 'root': 'pida', 'root_tokens': ['pida'], 'ending': '0', 'clitic': '', 'form': 'o', 'partofspeech': 'V'}, {'normalized_text': 'pea', 'lemma': 'pea', 'root': 'pea', 'root_tokens': ['pea'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('otsima', [{'normalized_text': 'otsima', 'lemma': 'otsima', 'root': 'otsi', 'root_tokens': ['otsi'], 'ending': 'ma', 'clitic': '', 'form': 'ma', 'partofspeech': 'V'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

### VabamorfWithBertTagger with verb corrections (correcting only verb annotation)

In [5]:
vbt2 = VabamorfWithBertTagger(use_postanalysis=True,
                            correct_verb_annotation=True,
                            change_to_bert_form=False)

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 366.60it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

In [6]:
txt2 = Text("Meie ei pea otsima.")
txt2.tag_layer(["words", "sentences"])

vbt2.tag( txt2 )
txt2["morph_analysis"]

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Meie', [{'normalized_text': 'Meie', 'lemma': 'mina', 'root': 'mina', 'root_tokens': ['mina'], 'ending': '0', 'clitic': '', 'form': 'pl n', 'partofspeech': 'P'}]),
Span('ei', [{'normalized_text': 'ei', 'lemma': 'ei', 'root': 'ei', 'root_tokens': ['ei'], 'ending': '0', 'clitic': '', 'form': 'neg', 'partofspeech': 'V'}]),
Span('pea', [{'normalized_text': 'pea', 'lemma': 'pidama', 'root': 'pida', 'root_tokens': ['pida'], 'ending': '0', 'clitic': '', 'form': 'o', 'partofspeech': 'V'}]),
Span('otsima', [{'normalized_text': 'otsima', 'lemma': 'otsima', 'root': 'otsi', 'root_tokens': ['otsi'], 'ending': 'ma', 'clitic': '', 'form': 'ma', 'partofspeech': 'V'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

### VabamorfWithBertTagger with verb corrections (correcting verb annotation and form)

In [7]:
vbt3 = VabamorfWithBertTagger(use_postanalysis=True,
                            correct_verb_annotation=True,
                            change_to_bert_form=True)

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 348.18it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

In [8]:
txt3 = Text("Meie ei pea otsima.")
txt3.tag_layer(["words", "sentences"])

vbt3.tag( txt3 )
txt3["morph_analysis"]

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Meie', [{'normalized_text': 'Meie', 'lemma': 'mina', 'root': 'mina', 'root_tokens': ['mina'], 'ending': '0', 'clitic': '', 'form': 'pl n', 'partofspeech': 'P'}]),
Span('ei', [{'normalized_text': 'ei', 'lemma': 'ei', 'root': 'ei', 'root_tokens': ['ei'], 'ending': '0', 'clitic': '', 'form': 'neg', 'partofspeech': 'V'}]),
Span('pea', [{'normalized_text': 'pea', 'lemma': 'pidama', 'root': 'pida', 'root_tokens': ['pida'], 'ending': '0', 'clitic': '', 'form': 'neg o', 'partofspeech': 'V'}]),
Span('otsima', [{'normalized_text': 'otsima', 'lemma': 'otsima', 'root': 'otsi', 'root_tokens': ['otsi'], 'ending': 'ma', 'clitic': '', 'form': 'ma', 'partofspeech': 'V'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

### VabamorfWithBertTagger: slang lex

By default, slang_lex flag is set to True. This helps to remove multiplicity for slang words.

In [9]:
# without slang lex
vbt4 = VabamorfWithBertTagger(use_postanalysis=True,
                            correct_verb_annotation=True,
                            change_to_bert_form=True,
                            slang_lex=False)

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 385.88it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

In [10]:
txt4 = Text("Ilm on mõnsa.")
txt4.tag_layer(["words", "sentences"])
vbt4.tag( txt4 )
txt4["morph_analysis"]

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Ilm', [{'normalized_text': 'Ilm', 'lemma': 'ilm', 'root': 'ilm', 'root_tokens': ['ilm'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('on', [{'normalized_text': 'on', 'lemma': 'olema', 'root': 'ole', 'root_tokens': ['ole'], 'ending': '0', 'clitic': '', 'form': 'b', 'partofspeech': 'V'}]),
Span('mõnsa', [{'normalized_text': 'mõnsa', 'lemma': 'mõnsa', 'root': 'mõnsa', 'root_tokens': ['mõnsa'], 'ending': '0', 'clitic': '', 'form': 'sg g', 'partofspeech': 'S'}, {'normalized_text': 'mõnsa', 'lemma': 'mõnsa', 'root': 'mõnsa', 'root_tokens': ['mõnsa'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

In [11]:
# with slang lex
vbt5 = VabamorfWithBertTagger(use_postanalysis=True,
                            correct_verb_annotation=True,
                            change_to_bert_form=True,
                             slang_lex=True)

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 389.91it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

In [12]:
txt5 = Text("Ilm on mõnsa.")
txt5.tag_layer(["words", "sentences"])
vbt5.tag( txt5 )
txt5["morph_analysis"]

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Ilm', [{'normalized_text': 'Ilm', 'lemma': 'ilm', 'root': 'ilm', 'root_tokens': ['ilm'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('on', [{'normalized_text': 'on', 'lemma': 'olema', 'root': 'ole', 'root_tokens': ['ole'], 'ending': '0', 'clitic': '', 'form': 'b', 'partofspeech': 'V'}]),
Span('mõnsa', [{'normalized_text': 'mõnsa', 'lemma': 'mõnsa', 'root': 'mõnsa', 'root_tokens': ['mõnsa'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'A'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])