# Bert-based morphological tagger and disambiguator (BertMorphTagger)

EstNLTK contains a Bert-based morphological tagger for annotating partofpseech and morphological form features in Estonian texts using [Vabamorf's tagset](00_tables_of_morphological_categories.ipynb). 
The tagger can also be used as a disambiguator to resolve ambiguities of an existing morphological analysis layer that uses Vabamorf's tagset. 
Bert-based morphological disambiguation is often more accurate than Vabamorf's morphological disambiguation, and can be additionally improved by adding an expert model for solving word form homonymy [(Saska 2026)](https://thesis.cs.ut.ee/8f10695d-4276-47ea-b306-5df66c034057).

## Prerequisites

*Note: you need to install [estnltk_neural](https://github.com/estnltk/estnltk/tree/main/estnltk_neural) and [sentencepiece](https://pypi.org/project/sentencepiece/) packages for using the Bert-based morphological tagger.*

Note that the Bert model required by the tagger is not distributed with the estnltk\_neural package. You can download the model in the following ways:
* If you create a new instance of `BertMorphTagger` and the model has not been downloaded yet, you'll be prompted with a question asking for a permission to download the model;
* Alternatively, you can pre-download the model manually via the download function:

```python
from estnltk import download
download('bert_morph_tagging')
```

Import modules

To use `BertMorphTagger`, you need to import BertMorphTagger from `estnltk_neural.taggers`:

In [1]:
import estnltk
from estnltk_neural.taggers import BertMorphTagger

C:\Programmid\Miniconda3\envs\py313_devel\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Using BertMorphTagger as a tagger

To initialize BertMorphTagger, call `BertMorphTagger` with preferred parameter values.

Important parameters for the tagger are:
* `get_top_n_predictions`: Output $n$ most probable morphological tags for each word. Defaults to **1**;
* `token_level`: If True outputs morphological tags for each BERT token, otherwise for each word in EstNLTK's `words` layer. Defaults to **False**;
* `split_pos_form`: If True splits predicted label into Vabamorf's tags `form` and `partofspeech`, otherwise outputs the label itself, which is a concatenation of previous Vabamorf's tags joined with `_`. Defaults to **True**

In [2]:
# morph_tagger = BertMorphTagger(get_top_n_predictions=1, token_level=False, split_pos_form=True) # With defined parameters
morph_tagger = BertMorphTagger() # Without defined parameters

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 311.43it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

`BertMorphTagger` relies on EstNLTK's `sentences` and `words` layer. Without it, tagger will not work.

In [3]:
input_str = "A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija."
text_obj = estnltk.Text(input_str)
# text_obj.tag_layer('sentences') # Without sentences and words layer
try:
    morph_tagger.tag(text_obj)
except ValueError as e:
    print(f"ValueError: {e}")

ValueError: missing input layer: 'sentences'

In [4]:
input_str = "A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija."
text_obj = estnltk.Text(input_str)
text_obj.tag_layer('sentences') # With sentences and words layer
morph_tagger.tag(text_obj)

Text(text='A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija.')

Accessing `bert_morph_tagging` layer.

In [5]:
text_obj['bert_morph_tagging']

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('A. H. Tammsaare', [{'bert_tokens': ['▁A', '.', '▁H', '.', '▁Tammsaare'], 'form': '', 'partofspeech': 'Y', 'probability': 0.99876}]),
Span('oli', [{'bert_tokens': ['▁oli'], 'form': 's', 'partofspeech': 'V', 'probability': 0.99994}]),
Span('eesti', [{'bert_tokens': ['▁eesti'], 'form': '', 'partofspeech': 'G', 'probability': 0.99924}]),
Span('kirjanik', [{'bert_tokens': ['▁kirjanik'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.9999}]),
Span(',', [{'bert_tokens': [','], 'form': '', 'partofspeech': 'Z', 'probability': 0.99998}]),
Span('esseist', [{'bert_tokens': ['▁es', 'se', 'ist'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99989}]),
Span(',', [{'bert_tokens': [','], 'form': '', 'partofspeech': 'Z', 'probability': 0.99998}]),
Span('kultuurifilosoof', [{'bert_tokens': ['▁kultuuri', 'filosoof'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99991}]),
Span('ja', [{'bert_tokens': ['▁ja'], 'form': '', 'partofspeech': 'J', 'probability': 0.99995}]),
Span('tõlkija', [{'bert_tokens': ['▁tõlkija'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99985}]),
Span('.', [{'bert_tokens': ['.'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99997}])])

BertMorphTagger generates four tags:
* `bert_tokens`: List of BERT tokens that are in one Vabamorf's word;
* `form`: Noun or verb form (following [Vabamorf's tagset](00_tables_of_morphological_categories.ipynb));
* `partofspeech`: Word's part of speech (following [Vabamorf's tagset](00_tables_of_morphological_categories.ipynb));
* `probability`: probability of generated tags.

Below is an example of one Vabamorf's word and its related BertMorphTagger's tokens.

In [6]:
print(f"""Vabamorf's word: {text_obj['words'][0].text}
BertMorphTagger's tokens: {text_obj['bert_morph_tagging'][0]['bert_tokens'][0]}""")

Vabamorf's word: A. H. Tammsaare
BertMorphTagger's tokens: ['▁A', '.', '▁H', '.', '▁Tammsaare']

By default, BertMorphTagger only outputs the most probable partofspeech/form tag for each word. 

However, you can use the parameter `get_top_n_predictions` to output more partofspeech/form interpretations. 

Example: let's change `get_top_n_predictions` parameter to 2 to output two top-most probability predictions for each word:

In [7]:
morph_tagger = BertMorphTagger(get_top_n_predictions=2)
input_str = "A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija."
text_obj = estnltk.Text(input_str)
text_obj.tag_layer('sentences') # With sentences and words layer
morph_tagger.tag(text_obj)
text_obj['bert_morph_tagging']

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 370.01it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('A. H. Tammsaare', [{'bert_tokens': ['▁A', '.', '▁H', '.', '▁Tammsaare'], 'form': '', 'partofspeech': 'Y', 'probability': 0.99876}, {'bert_tokens': ['▁A', '.', '▁H', '.', '▁Tammsaare'], 'form': '', 'partofspeech': 'S', 'probability': 0.00014}]),
Span('oli', [{'bert_tokens': ['▁oli'], 'form': 's', 'partofspeech': 'V', 'probability': 0.99994}, {'bert_tokens': ['▁oli'], 'form': 'sin', 'partofspeech': 'V', 'probability': 1e-05}]),
Span('eesti', [{'bert_tokens': ['▁eesti'], 'form': '', 'partofspeech': 'G', 'probability': 0.99924}, {'bert_tokens': ['▁eesti'], 'form': 'sg g', 'partofspeech': 'H', 'probability': 0.0001}]),
Span('kirjanik', [{'bert_tokens': ['▁kirjanik'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.9999}, {'bert_tokens': ['▁kirjanik'], 'form': 'pl n', 'partofspeech': 'S', 'probability': 1e-05}]),
Span(',', [{'bert_tokens': [','], 'form': '', 'partofspeech': 'Z', 'probability': 0.99998}, {'bert_tokens': [','], 'form': '', 'partofspeech': 'J', 'probability': 1e-05}]),
Span('esseist', [{'bert_tokens': ['▁es', 'se', 'ist'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99989}, {'bert_tokens': ['▁es', 'se', 'ist'], 'form': 'pl n', 'partofspeech': 'S', 'probability': 1e-05}]),
Span(',', [{'bert_tokens': [','], 'form': '', 'partofspeech': 'Z', 'probability': 0.99998}, {'bert_tokens': [','], 'form': '', 'partofspeech': 'J', 'probability': 0.0}]),
Span('kultuurifilosoof', [{'bert_tokens': ['▁kultuuri', 'filosoof'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99991}, {'bert_tokens': ['▁kultuuri', 'filosoof'], 'form': 'sg p', 'partofspeech': 'S', 'probability': 1e-05}]),
Span('ja', [{'bert_tokens': ['▁ja'], 'form': '', 'partofspeech': 'J', 'probability': 0.99995}, {'bert_tokens': ['▁ja'], 'form': 'pl p', 'partofspeech': 'S', 'probability': 0.0}]),
Span('tõlkija', [{'bert_tokens': ['▁tõlkija'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99985}, {'bert_tokens': ['▁tõlkija'], 'form': 'sg g', 'partofspeech': 'S', 'probability': 4e-05}]),
Span('.', [{'bert_tokens': ['.'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99997}, {'bert_tokens': ['.'], 'form': '', 'partofspeech': 'J', 'probability': 0.0}])])

Parameter `token_level` can be used to switch tokenization of the output layer from the EstNLTK's words layer (the default setting) to original tokenization that was produced by the tokenizer of the Bert model. 

Example: changing `token_level` parameter to **True**:

In [8]:
morph_tagger = BertMorphTagger(token_level=True)
input_str = "A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija."
text_obj = estnltk.Text(input_str)
text_obj.tag_layer('sentences') # With sentences and words layer
morph_tagger.tag(text_obj)
text_obj['bert_morph_tagging']

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 381.71it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('A', [{'bert_tokens': '▁A', 'form': '', 'partofspeech': 'Y', 'probability': 0.99876}]),
Span('.', [{'bert_tokens': '.', 'form': '', 'partofspeech': 'Y', 'probability': 0.99415}]),
Span(' H', [{'bert_tokens': '▁H', 'form': '', 'partofspeech': 'Y', 'probability': 0.99865}]),
Span('.', [{'bert_tokens': '.', 'form': '', 'partofspeech': 'Y', 'probability': 0.98086}]),
Span(' Tammsaare', [{'bert_tokens': '▁Tammsaare', 'form': 'sg n', 'partofspeech': 'H', 'probability': 0.99959}]),
Span(' oli', [{'bert_tokens': '▁oli', 'form': 's', 'partofspeech': 'V', 'probability': 0.99994}]),
Span(' eesti', [{'bert_tokens': '▁eesti', 'form': '', 'partofspeech': 'G', 'probability': 0.99924}]),
Span(' kirjanik', [{'bert_tokens': '▁kirjanik', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.9999}]),
Span(',', [{'bert_tokens': ',', 'form': '', 'partofspeech': 'Z', 'probability': 0.99998}]),
Span(' es', [{'bert_tokens': '▁es', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99989}]),
Span('se', [{'bert_tokens': 'se', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99988}]),
Span('ist', [{'bert_tokens': 'ist', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99986}]),
Span(',', [{'bert_tokens': ',', 'form': '', 'partofspeech': 'Z', 'probability': 0.99998}]),
Span(' kultuuri', [{'bert_tokens': '▁kultuuri', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99991}]),
Span('filosoof', [{'bert_tokens': 'filosoof', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.9999}]),
Span(' ja', [{'bert_tokens': '▁ja', 'form': '', 'partofspeech': 'J', 'probability': 0.99995}]),
Span(' tõlkija', [{'bert_tokens': '▁tõlkija', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99985}]),
Span('.', [{'bert_tokens': '.', 'form': '', 'partofspeech': 'Z', 'probability': 0.99997}])])

Parameter `split_pos_form` can be used to alternate between outputting `partofspeech` and `form` as separate features (the default setting), and outputting a single morphological tag (the attribute `morph_label`).

Example: changing `split_pos_form` parameter to **False**:

In [9]:
morph_tagger = BertMorphTagger(split_pos_form=False)
input_str = "A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija."
text_obj = estnltk.Text(input_str)
text_obj.tag_layer('sentences') # With sentences and words layer
morph_tagger.tag(text_obj)
text_obj['bert_morph_tagging']

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 430.56it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'morph_label', 'probability'), spans=SL[Span('A. H. Tammsaare', [{'bert_tokens': ['▁A', '.', '▁H', '.', '▁Tammsaare'], 'morph_label': 'Y', 'probability': 0.99876}]),
Span('oli', [{'bert_tokens': ['▁oli'], 'morph_label': 's_V', 'probability': 0.99994}]),
Span('eesti', [{'bert_tokens': ['▁eesti'], 'morph_label': 'G', 'probability': 0.99924}]),
Span('kirjanik', [{'bert_tokens': ['▁kirjanik'], 'morph_label': 'sg n_S', 'probability': 0.9999}]),
Span(',', [{'bert_tokens': [','], 'morph_label': 'Z', 'probability': 0.99998}]),
Span('esseist', [{'bert_tokens': ['▁es', 'se', 'ist'], 'morph_label': 'sg n_S', 'probability': 0.99989}]),
Span(',', [{'bert_tokens': [','], 'morph_label': 'Z', 'probability': 0.99998}]),
Span('kultuurifilosoof', [{'bert_tokens': ['▁kultuuri', 'filosoof'], 'morph_label': 'sg n_S', 'probability': 0.99991}]),
Span('ja', [{'bert_tokens': ['▁ja'], 'morph_label': 'J', 'probability': 0.99995}]),
Span('tõlkija', [{'bert_tokens': ['▁tõlkija'], 'morph_label': 'sg n_S', 'probability': 0.99985}]),
Span('.', [{'bert_tokens': ['.'], 'morph_label': 'Z', 'probability': 0.99997}])])

As you can see above, tags `form` and `partofspeech` are concatenated into one tag `morph_label`.

### Using hardware acceleration (GPU)

Use the parameter `device` to switch from CPU (default) to a GPU to speed up the processing, for example:

```python
from estnltk_neural.taggers import BertMorphTagger
morph_tagger = BertMorphTagger(device='cuda')  # use GPU
```

Note that this requires that you have the corresponding hardware available. By default, no hardware acceleration is used. 
For other possible `device` values, please consult [pytorch device documentation](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch.device).

## Using BertMorphTagger as a disambiguator

If the flag `disambiguate` is set to `True`, then the tagger can be used as an disambiguator (retagger) of an existing Vabamorf-based morph analysis layer. For this, the `output_layer` name also needs to be changed to the name of the morph analysis layer, which will become the input layer of the tagger.

Example

In [10]:
from estnltk import Text
from estnltk_neural.taggers import BertMorphTagger

In [11]:
# initialize BertMorphTagger as a disambiguator
morph_disambiguator = BertMorphTagger(output_layer='morph_analysis', disambiguate=True)

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 389.25it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

In [12]:
morph_disambiguator.input_layers

('sentences', 'words', 'morph_analysis')

In [13]:
# Use Vabamorf's analyzer to create an ambiguous morph analysis layer
from estnltk.taggers import VabamorfAnalyzer
vm_analyzer = VabamorfAnalyzer()
text = Text("Üks kärbes hulbib mees ja naeris teeb head lobi.")
text.tag_layer( vm_analyzer.input_layers )
vm_analyzer.tag(text)
text['morph_analysis']

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Üks', [{'normalized_text': 'Üks', 'lemma': 'üks', 'root': 'üks', 'root_tokens': ['üks'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'N'}, {'normalized_text': 'Üks', 'lemma': 'üks', 'root': 'üks', 'root_tokens': ['üks'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'P'}]),
Span('kärbes', [{'normalized_text': 'kärbes', 'lemma': 'kärbes', 'root': 'kärbes', 'root_tokens': ['kärbes'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('hulbib', [{'normalized_text': 'hulbib', 'lemma': 'hulpima', 'root': 'hulpi', 'root_tokens': ['hulpi'], 'ending': 'b', 'clitic': '', 'form': 'b', 'partofspeech': 'V'}]),
Span('mees', [{'normalized_text': 'mees', 'lemma': 'mees', 'root': 'mees', 'root_tokens': ['mees'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}, {'normalized_text': 'mees', 'lemma': 'mesi', 'root': 'mesi', 'root_tokens': ['mesi'], 'ending': 's', 'clitic': '', 'form': 'sg in', 'partofspeech': 'S'}]),
Span('ja', [{'normalized_text': 'ja', 'lemma': 'ja', 'root': 'ja', 'root_tokens': ['ja'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'J'}]),
Span('naeris', [{'normalized_text': 'naeris', 'lemma': 'naerma', 'root': 'naer', 'root_tokens': ['naer'], 'ending': 'is', 'clitic': '', 'form': 's', 'partofspeech': 'V'}, {'normalized_text': 'naeris', 'lemma': 'naeris', 'root': 'naeris', 'root_tokens': ['naeris'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}, {'normalized_text': 'naeris', 'lemma': 'naeris', 'root': 'naeris', 'root_tokens': ['naeris'], 'ending': 's', 'clitic': '', 'form': 'sg in', 'partofspeech': 'S'}]),
Span('teeb', [{'normalized_text': 'teeb', 'lemma': 'tegema', 'root': 'tege', 'root_tokens': ['tege'], 'ending': 'b', 'clitic': '', 'form': 'b', 'partofspeech': 'V'}]),
Span('head', [{'normalized_text': 'head', 'lemma': 'hea', 'root': 'hea', 'root_tokens': ['hea'], 'ending': 'd', 'clitic': '', 'form': 'pl n', 'partofspeech': 'A'}, {'normalized_text': 'head', 'lemma': 'hea', 'root': 'hea', 'root_tokens': ['hea'], 'ending': 'd', 'clitic': '', 'form': 'sg p', 'partofspeech': 'A'}, {'normalized_text': 'head', 'lemma': 'hea', 'root': 'hea', 'root_tokens': ['hea'], 'ending': 'd', 'clitic': '', 'form': 'pl n', 'partofspeech': 'S'}, {'normalized_text': 'head', 'lemma': 'hea', 'root': 'hea', 'root_tokens': ['hea'], 'ending': 'd', 'clitic': '', 'form': 'sg p', 'partofspeech': 'S'}]),
Span('lobi', [{'normalized_text': 'lobi', 'lemma': 'lobi', 'root': 'lobi', 'root_tokens': ['lobi'], 'ending': '0', 'clitic': '', 'form': 'sg g', 'partofspeech': 'S'}, {'normalized_text': 'lobi', 'lemma': 'lobima', 'root': 'lobi', 'root_tokens': ['lobi'], 'ending': '0', 'clitic': '', 'form': 'o', 'partofspeech': 'V'}, {'normalized_text': 'lobi', 'lemma': 'lobi', 'root': 'lobi', 'root_tokens': ['lobi'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}, {'normalized_text': 'lobi', 'lemma': 'lobi', 'root': 'lobi', 'root_tokens': ['lobi'], 'ending': '0', 'clitic': '', 'form': 'sg p', 'partofspeech': 'S'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

In [14]:
# Use BertMorphTagger to disambiguate the layer
morph_disambiguator.retag( text )
text['morph_analysis']

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Üks', [{'normalized_text': 'Üks', 'lemma': 'üks', 'root': 'üks', 'root_tokens': ['üks'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'P'}]),
Span('kärbes', [{'normalized_text': 'kärbes', 'lemma': 'kärbes', 'root': 'kärbes', 'root_tokens': ['kärbes'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('hulbib', [{'normalized_text': 'hulbib', 'lemma': 'hulpima', 'root': 'hulpi', 'root_tokens': ['hulpi'], 'ending': 'b', 'clitic': '', 'form': 'b', 'partofspeech': 'V'}]),
Span('mees', [{'normalized_text': 'mees', 'lemma': 'mees', 'root': 'mees', 'root_tokens': ['mees'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('ja', [{'normalized_text': 'ja', 'lemma': 'ja', 'root': 'ja', 'root_tokens': ['ja'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'J'}]),
Span('naeris', [{'normalized_text': 'naeris', 'lemma': 'naeris', 'root': 'naeris', 'root_tokens': ['naeris'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('teeb', [{'normalized_text': 'teeb', 'lemma': 'tegema', 'root': 'tege', 'root_tokens': ['tege'], 'ending': 'b', 'clitic': '', 'form': 'b', 'partofspeech': 'V'}]),
Span('head', [{'normalized_text': 'head', 'lemma': 'hea', 'root': 'hea', 'root_tokens': ['hea'], 'ending': 'd', 'clitic': '', 'form': 'sg p', 'partofspeech': 'A'}]),
Span('lobi', [{'normalized_text': 'lobi', 'lemma': 'lobi', 'root': 'lobi', 'root_tokens': ['lobi'], 'ending': '0', 'clitic': '', 'form': 'sg p', 'partofspeech': 'S'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

As for the limitation, the disambiguator does not resolve lemma ambiguities ( such as the ambiguity of the word _'teod'_ between lemmas _'tegu'_ and _'tigu'_ ).

## Using BertMorphTagger with homonymous word forms post-correction

`BertMorphTagger` accepts parameter `post_disambiguator`, which can be a retagger that refines / post-corrects Bert's predictions. 
While there is no post-correction by default, you can initialize the parameter with `MorphHomonymsRetagger` for post-correcting homonymous words. 
This will apply the expert model [Ro-v2-H](https://huggingface.co/tartuNLP/est-roberta-vm-morph-homonym-tagging), which disambiguates homonymous words from inflectional types 1, 16, 17 and 19. The model creation and evaluation process are described by [Saska (2026)](https://thesis.cs.ut.ee/8f10695d-4276-47ea-b306-5df66c034057).

#### Prerequisites

Note that the Bert model required by `MorphHomonymsRetagger` is not distributed with the estnltk\_neural package. You can download the model in the following ways:
* If you create a new instance of `MorphHomonymsRetagger` and the model has not been downloaded yet, you'll be prompted with a question asking for a permission to download the model;
* Alternatively, you can pre-download the model manually via the download function:
```python
from estnltk import download
download('morph_homonymy_expert')
```

In [15]:
from estnltk import Text
from estnltk_neural.taggers import BertMorphTagger
from estnltk_neural.taggers import MorphHomonymsRetagger

**Example.**
Use the default model, which can produce errors in analysing homonymous word forms:

In [16]:
morph_tagger_1 = BertMorphTagger()
text = Text("Mis oleks, kui täidaks muna maasikate ja šokolaadi ning pähklitega?")
text.tag_layer( morph_tagger_1.input_layers )
morph_tagger_1.tag(text)
display(text.bert_morph_tagging)

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 385.36it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('Mis', [{'bert_tokens': ['▁Mis'], 'form': 'sg n', 'partofspeech': 'P', 'probability': 0.99989}]),
Span('oleks', [{'bert_tokens': ['▁oleks'], 'form': 'ks', 'partofspeech': 'V', 'probability': 0.99988}]),
Span(',', [{'bert_tokens': [','], 'form': '', 'partofspeech': 'Z', 'probability': 0.99995}]),
Span('kui', [{'bert_tokens': ['▁kui'], 'form': '', 'partofspeech': 'J', 'probability': 0.99992}]),
Span('täidaks', [{'bert_tokens': ['▁täida', 'ks'], 'form': 'ks', 'partofspeech': 'V', 'probability': 0.99953}]),
Span('muna', [{'bert_tokens': ['▁muna'], 'form': 'sg g', 'partofspeech': 'S', 'probability': 0.94677}]),
Span('maasikate', [{'bert_tokens': ['▁maas', 'ikate'], 'form': 'pl g', 'partofspeech': 'S', 'probability': 0.99978}]),
Span('ja', [{'bert_tokens': ['▁ja'], 'form': '', 'partofspeech': 'J', 'probability': 0.99994}]),
Span('šokolaadi', [{'bert_tokens': ['▁šokolaadi'], 'form': 'sg g', 'partofspeech': 'S', 'probability': 0.99974}]),
Span('ning', [{'bert_tokens': ['▁ning'], 'form': '', 'partofspeech': 'J', 'probability': 0.99994}]),
Span('pähklitega', [{'bert_tokens': ['▁pähk', 'litega'], 'form': 'pl kom', 'partofspeech': 'S', 'probability': 0.99966}]),
Span('?', [{'bert_tokens': ['?'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99931}])])

For comparison, use the Bert model with an expert model that corrects homonymous words:

In [17]:
morph_tagger_2 = BertMorphTagger( post_disambiguator=MorphHomonymsRetagger() )
text = Text("Mis oleks, kui täidaks muna maasikate ja šokolaadi ning pähklitega?")
text.tag_layer( morph_tagger_2.input_layers )
morph_tagger_2.tag(text)
display(text.bert_morph_tagging)

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 334.33it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 376.66it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('Mis', [{'bert_tokens': ['▁Mis'], 'form': 'sg n', 'partofspeech': 'P', 'probability': 0.99989}]),
Span('oleks', [{'bert_tokens': ['▁oleks'], 'form': 'ks', 'partofspeech': 'V', 'probability': 0.99988}]),
Span(',', [{'bert_tokens': [','], 'form': '', 'partofspeech': 'Z', 'probability': 0.99995}]),
Span('kui', [{'bert_tokens': ['▁kui'], 'form': '', 'partofspeech': 'J', 'probability': 0.99992}]),
Span('täidaks', [{'bert_tokens': ['▁täida', 'ks'], 'form': 'ks', 'partofspeech': 'V', 'probability': 0.99953}]),
Span('muna', [{'bert_tokens': ['▁muna'], 'form': 'sg p', 'partofspeech': 'S', 'probability': 0.99999}]),
Span('maasikate', [{'bert_tokens': ['▁maas', 'ikate'], 'form': 'pl g', 'partofspeech': 'S', 'probability': 0.99978}]),
Span('ja', [{'bert_tokens': ['▁ja'], 'form': '', 'partofspeech': 'J', 'probability': 0.99994}]),
Span('šokolaadi', [{'bert_tokens': ['▁šokolaadi'], 'form': 'sg g', 'partofspeech': 'S', 'probability': 0.99974}]),
Span('ning', [{'bert_tokens': ['▁ning'], 'form': '', 'partofspeech': 'J', 'probability': 0.99994}]),
Span('pähklitega', [{'bert_tokens': ['▁pähk', 'litega'], 'form': 'pl kom', 'partofspeech': 'S', 'probability': 0.99966}]),
Span('?', [{'bert_tokens': ['?'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99931}])])

**Hardware acceleration (GPU)**. If you want to use a GPU to speed up the processing, then initialize MorphHomonymsRetagger with  the parameter `device` set to 'cuda':
```python
from estnltk_neural.taggers import MorphHomonymsRetagger
expert_model = MorphHomonymsRetagger(device='cuda')  # use GPU
```

Note that this requires that you have the corresponding hardware available. By default, no hardware acceleration is used. 
For other possible `device` values, please consult [pytorch device documentation](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch.device).

#### Verb post-corrections on disambiguation

Changing flags `correct_verb_annotation` and `change_to_bert_form` in `BertMorphTagger`'s determines whether Vabamorf's analyses are post-corrected during BertMorpTagger's disambiguation. 

* `correct_verb_annotation=True` (default) makes the disambiguator to prefer verb analyses iff the Bert model predicts verb part of speech, but the form predicted by the Bert model cannot be matched with any of Vabamorf's forms. This is usually the case with neg verb forms, which Vabamorf does not assign correctly: for instance, iff Bert predicts `'V neg o'`, and the only Vabamorf's verb analysis is `'V o'`, then `'V o'` is chosen despite the mismatch of forms (`'neg o' != 'o'`);
* `change_to_bert_form=True` (default) makes the disambiguator to change / post-correct verb forms in Vabamorf's analyses based on Bert's predictions (e.g. changes Vabamorf's form `'o'` to `'neg o'` if Bert predicts `'neg o'`);

When there is no verb ambiguity, then for 91% of the time (1789/1945 cases on UD treebank 2.18), the Bert's verb analysis improves the Vabamorf analysis (if `correct_verb_annotation=True`). This is mostly because of "neg" in Bert's form analysis.

---

## Training and performance evaluation

Source code for fine-tuning the model and evaluating its performance can be found from the repository: https://github.com/estnltk/estnltk-model-training/tree/main/morph_tagging