## BertTagger

BERT (Bidirectional Encoder Representations from Transformers) developed by Google is a method of pre-training language representations. 
[Devlin et al. (2019)](https://arxiv.org/pdf/1810.04805.pdf) introduces the Bert model, and the Estonian specific EstBERT model is proposed by [Tanvir et al. (2021)](https://aclanthology.org/2021.nodalida-main.2).

We can use pre-trained BERT models to get contextual embeddings for sentences. 

*Note: you need to install [estnltk_neural](https://github.com/estnltk/estnltk/tree/main/estnltk_neural) package for using this functionality.*

`esnltk_neural` provides BertTagger for computing contextual embeddings for tokens and words. The model required by the tagger needs to be downloaded separately. There are two ways for downloading the model:

* If you create a new instance of BertTagger and the model has not been downloaded yet, you'll be prompted with a question asking for permission to download the model;
* Alternatively, you can pre-download model manually via download function:

In [1]:
from estnltk import download
download('berttagger')

Resource 'estbert_from_tartunlp_hf_2022-03-10' has already been downloaded.

True

Now, let's use the model with BertTagger:

In [2]:
from estnltk import Text
from estnltk_neural.taggers import BertTagger

In [3]:
bert_tagger = BertTagger()

Some weights of BertModel were not initialized from the model checkpoint at C:\Programmid\Miniconda3\envs\py312_devel\Lib\site-packages\estnltk\estnltk_resources\estbert\model_hf_tartunlp_2022-03-10\ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

**Providing model manually.** Alternatively, we can also manually download the EstBERT model from [here](https://huggingface.co/tartuNLP/EstBERT#). 
Once the model is downloaded, we should have the following files in the downloaded folder: <br>
<ul>
 <li>  bert_config.json </li>
 <li>  config.json </li>
 <li>  pytorch_model.bin </li>
 <li>  special_tokens_map.json </li>
 <li>  tokenizer_config.json </li>
 <li>  model.ckpt.data-00000-of-00001 </li>
 <li>  model.ckpt.index </li>
 <li>  model.ckpt.meta </li>
 <li>  vocab.txt </li>
</ul>

Then we can use the bert_location parameter to specify the location of the model directory:

```python
from estnltk_neural.taggers import BertTagger
# Specify the location of the model manually
bert_tagger = BertTagger(bert_location='C:/Users/kittask/Documents/multilingual_bert')
```

BertTagger expects sentences layer to be present, so we need to tag the layer:

In [4]:
text = Text("Aga mulle tundub, et kogu maailm ootab muusikamaailmalt midagi erutavalt uut minimalismi kõrvale.")
text.tag_layer('sentences')

Text(text='Aga mulle tundub, et kogu maailm ootab muusikamaailmalt midagi erutavalt uut minimalismi kõrvale.')

In [5]:
bert_tagger.tag(text)

Text(text='Aga mulle tundub, et kogu maailm ootab muusikamaailmalt midagi erutavalt uut minimalismi kõrvale.')

BertTagger created new layer called bert_embeddings. By default, it annotates tokens tokenized with BertTokenizer and not full words.

In [6]:
text.bert_embeddings

Layer(name='bert_embeddings', attributes=('token', 'bert_embedding'), spans=SL[Span('Aga', [{'token': 'aga', 'bert_embedding': [0.3278188109397888, -0.16953623294830322, 0.2002796232700348, -0.07365242391824722, 0.14430496096611023, 0.20451723039150238, -0.02085014060139656, -0.29243314266204834, 0.09826085716485977, -1.191714882850647, -0.3223409950733185, -0.33028796315193176, 0.183272123336792, 0.5862610936164856, 0.04625318944454193, -0.40418189764022827, -0.2801961600780487, 0.04790060222148895, -0.3883582055568695, 0.17735958099365234, -0.5762463808059692, -0.004837486892938614, 0.2307850420475006, 0.5093223452568054, 0.09094486385583878, 0.15685522556304932, -0.03035348653793335, -0.11316829919815063, -0.7863669395446777, 0.28760427236557007, -0.0007256306707859039, -0.10174038261175156, -0.039974719285964966, -0.384290874004364, 0.335353821516037, -0.15197701752185822, -0.11477428674697876, 0.5075159668922424, -0.8984876871109009, -0.9749445915222168, -0.5450775623321533, -0.18286336958408356, -0.1099361926317215, -0.161588653922081, -0.570109486579895, -0.4941341280937195, -0.13684816658496857, 0.4860466718673706, 0.17140936851501465, 0.24095308780670166, -0.17532268166542053, 0.3228375315666199, -0.06616385281085968, -0.3962583839893341, -0.486549437046051, 0.3367096483707428, -0.6223149299621582, -0.8136024475097656, -1.0135481357574463, -0.19160383939743042, -0.2433304786682129, 0.40373679995536804, 0.6047642827033997, 0.39473986625671387, 0.23971664905548096, 0.8521662950515747, -0.5547722578048706, 0.2493463009595871, -0.23879805207252502, 0.13893043994903564, -0.000838360982015729, 0.5913722515106201, -0.40748852491378784, 0.5568178296089172, 0.16842472553253174, -0.2291041910648346, 0.13290980458259583, 0.46030446887016296, 0.8170680999755859, 0.27015024423599243, 0.3512106239795685, -0.13367332518100739, -0.024103445932269096, 0.4181838631629944, 0.7882547974586487, 0.08487904071807861, -0.3317407965660095, 0.14242365956306458, -0.38008713722229004, 0.425761878490448, -0.7242530584335327, -0.07148750871419907, -0.07830376923084259, 0.10971781611442566, -0.386206716299057, -0.012895360589027405, -0.7104009985923767, 0.30355364084243774, -0.1168847605586052, -0.3752098083496094, 0.2121637910604477, 0.7487406134605408, 0.06567458063364029, -1.202872633934021, 0.11779771000146866, 0.2672608494758606, -1.0046249628067017, -0.08382822573184967, -0.27730974555015564, 0.2235480695962906, -0.43390190601348877, 0.25553005933761597, -0.28693127632141113, -0.3699626624584198, 0.16292475163936615, 0.018925946205854416, -0.1565748155117035, 0.4325149655342102, 0.34266865253448486, 0.5192920565605164, -0.7768000364303589, -0.5375838279724121, 0.14567360281944275, -0.2180250883102417, 0.029793977737426758, -0.09148609638214111, 0.3554029166698456, -0.44299572706222534, 0.5198879837989807, 0.2840366065502167, -0.9541960954666138, -0.7293714880943298, -0.5290390253067017, -0.4005843997001648, -0.04212985187768936, -0.09765373170375824, 0.3197008967399597, 0.019579578191041946, -0.26574042439460754, -0.4147486686706543, -0.3810008764266968, -0.11509539932012558, 0.006800223141908646, 0.18359142541885376, -0.15650901198387146, -0.03674929961562157, 0.5559682250022888, -0.4014148414134979, 0.16074834764003754, 0.1987924426794052, -0.029863178730010986, -0.5618911981582642, 0.3736233413219452, -0.12158270925283432, 1.1459102630615234, 0.04828975349664688, 0.003614187240600586, -0.2175644338130951, -0.26649779081344604, 0.34649360179901123, 0.02331715077161789, 0.21271145343780518, -0.382511705160141, 0.13624101877212524, -0.5414584875106812, 0.7361845970153809, 0.21834184229373932, 1.0671074390411377, -1.0489705801010132, -0.21201878786087036, -0.5297546982765198, -0.6545546650886536, 0.1993209570646286, 0.36346209049224854, -0.27066293358802795, 0.39945846796035767, -0.8434147238731384, 1.5994670391082764, -0.018822863698005676, 0.5178473591804504, 0.019160844385623932, -0.21594296395778656, -0.09390510618686676, 0.30184900760650635, -0.2094270884990692, -0.526375412940979, 0.16406367719173431, -0.5772994160652161, 0.9714956879615784, -0.4942685663700104, -1.2075387239456177, -0.40797460079193115, -0.3818889260292053, -0.7075055837631226, 0.9583442211151123, -0.1199059709906578, -0.8907995820045471, 0.161105677485466, 0.558539628982544, 0.2091776728630066, -0.48729264736175537, -0.35874056816101074, 0.44080108404159546, -0.06761537492275238, 0.2565144896507263, -0.1882876455783844, -0.5016840100288391, 0.428050696849823, -0.734359622001648, 0.04076734185218811, 0.23275189101696014, -0.11557243019342422, 0.05653105676174164, 0.8012708425521851, 0.0736386626958847, 1.412176251411438, -0.35470616817474365, -0.19732126593589783, 0.19100746512413025, -0.007862333208322525, 0.7504048347473145, 0.2932165861129761, 0.1472848653793335, -0.7042785286903381, -0.14819398522377014, 4.361918926239014, -0.09522859752178192, -0.4527125358581543, -0.013385772705078125, 0.0644034668803215, 0.4320114850997925, 0.2666911780834198, -0.406225323677063, 0.026966311037540436, 0.013701915740966797, -0.4970378279685974, 0.27163630723953247, -0.18664135038852692, 0.17901983857154846, 1.7284657955169678, 0.3257840871810913, 0.33020007610321045, 0.08085734397172928, -0.13880842924118042, 0.7088090777397156, 0.05671953037381172, -0.16286835074424744, 0.7758722305297852, -0.8486196398735046, 0.19456912577152252, 0.1062730997800827, 0.42236924171447754, -0.14216220378875732, -0.3754599988460541, 0.781653106212616, 0.03228700906038284, 0.3218997120857239, 0.28450316190719604, -0.5374008417129517, 0.058817893266677856, 0.35462045669555664, 0.3582177758216858, 0.11847756803035736, -0.20597997307777405, -0.15014371275901794, 0.7851737141609192, 2.252208948135376, 0.0026590158231556416, 0.19418483972549438, -2.438754081726074, -0.3594406843185425, 0.15598638355731964, -0.18441933393478394, 0.2592705488204956, 0.06336140632629395, 0.2570417821407318, -0.35954636335372925, 0.5086755156517029, -0.1253003180027008, -0.7561280131340027, 0.16910302639007568, 0.3657380938529968, 0.6044049263000488, 0.465615451335907, -0.12270055711269379, -0.24863195419311523, -0.27994662523269653, -0.34942227602005005, 0.06560864299535751, -0.047925688326358795, 0.21816523373126984, -0.11040842533111572, 0.0010752315865829587, 0.7384392023086548, 0.3211783468723297, 0.13209973275661469, -0.3883522152900696, 0.19436432421207428, 0.7200573086738586, 0.27370545268058777, -0.11111345142126083, -0.08648601174354553, 0.048138052225112915, 0.25146162509918213, -0.2130255252122879, -1.1770641803741455, -0.6487868428230286, 0.2603120803833008, 0.22950062155723572, 0.21386423707008362, -0.1941390186548233, -0.03461397439241409, 0.05552060157060623, 0.327972412109375, -0.0921090692281723, -0.6634544730186462, 0.34067249298095703, -0.4246043562889099, -0.07475228607654572, 0.18456536531448364, 0.4301227331161499, 0.26673850417137146, 0.007438838481903076, -0.27299821376800537, -0.18258675932884216, 0.7752748727798462, -0.3888525366783142, -0.32269424200057983, -0.008763115853071213, 0.08283612132072449, 0.15514741837978363, -0.31448620557785034, 0.18774348497390747, 0.013300806283950806, -0.17999912798404694, 0.6301891207695007, -0.8595724701881409, -0.424696683883667, 0.31611183285713196, 0.1347154974937439, -0.18285730481147766, 0.35935840010643005, -0.8008666634559631, -0.29622888565063477, 0.1833132803440094, -0.5664783716201782, -0.4522911608219147, 0.007952714338898659, -0.3896107077598572, -0.12898512184619904, 0.6095991730690002, 0.6571648120880127, 0.4133320450782776, -0.08864434063434601, 0.2252870798110962, 0.023499339818954468, 0.028267376124858856, -0.27448582649230957, 0.2528391182422638, -0.02231934666633606, 0.18234024941921234, -1.0839135646820068, -0.49588823318481445, 0.2424900233745575, -0.5700171589851379, 0.26161816716194153, -0.47536328434944153, 0.03312482684850693, 0.06936370581388474, 0.10991626232862473, 0.3987729847431183, -0.44528335332870483, -0.33443722128868103, 0.3933902382850647, 0.3663717806339264, -0.5966441631317139, -0.5817736983299255, 1.0741771459579468, 0.786790132522583, -0.27877289056777954, 0.17929163575172424, 0.4026017189025879, 0.019568391144275665, -0.005575145594775677, 0.18172353506088257, 0.3037291169166565, 0.26043280959129333, -0.1260516196489334, 0.10631326586008072, -0.4440390467643738, -0.1408153623342514, 0.0010748356580734253, -0.29774218797683716, 0.10186804085969925, -6.793895244598389, 0.11001376807689667, -0.35561463236808777, -0.6976473331451416, 0.005806386470794678, 0.2919827103614807, -0.3355211615562439, -0.39485734701156616, 0.08403173834085464, 0.34856143593788147, 0.08788704127073288, 0.783156156539917, 0.6021463871002197, -0.22744420170783997, 0.2778876721858978, 0.267961323261261, 0.14817142486572266, 0.23137035965919495, -0.1967628002166748, -0.3147733509540558, -0.37109023332595825, 0.09280091524124146, 0.04836845025420189, 0.3188213109970093, -0.26410800218582153, 0.18275992572307587, 0.6589000225067139, 0.2061065137386322, 1.087146520614624, -0.5014020204544067, 0.06942419707775116, 0.13354277610778809, 0.12926369905471802, 0.37110239267349243, -0.3128764033317566, 0.3313922584056854, 0.1760762333869934, 0.0014252420514822006, -0.04152284562587738, 0.4612448811531067, 0.6355089545249939, -0.1832820624113083, 0.6171593070030212, -0.7143099904060364, -0.2539779245853424, 0.4250946044921875, 0.18306902050971985, -0.6570613980293274, -0.3871019780635834, 0.02985655516386032, -0.34634238481521606, 0.9016390442848206, -0.3036847710609436, -0.7305542230606079, 0.6070414185523987, -0.801563560962677, -0.053710564970970154, 1.1160235404968262, 0.19456559419631958, -0.4091368317604065, -0.19218900799751282, 1.0340421199798584, 0.20662155747413635, 0.38304635882377625, 0.2700166702270508, 0.12833142280578613, 0.8618882298469543, 0.10214880108833313, 0.6530033946037292, -0.24164065718650818, 0.2797682285308838, -0.06079387664794922, -6.987588405609131, 0.3653864860534668, 0.22416004538536072, -0.5897541642189026, 1.3279774188995361, -0.2546006739139557, -0.14766451716423035, 0.25859156250953674, -0.30267849564552307, 0.2681120038032532, 0.03274111449718475, 0.4471808075904846, -0.8802198767662048, 0.10994384437799454, -0.5036477446556091, -0.12375378608703613, -0.3593243658542633, -0.4616542458534241, -0.3453715443611145, 0.11590364575386047, -0.43340155482292175, -0.06660613417625427, -0.380312442779541, -0.03460356593132019, -0.38102343678474426, -0.8173595666885376, 0.969663679599762, 0.3026373088359833, -0.11873900890350342, 0.5838533639907837, -1.0581756830215454, -0.14444279670715332, 0.1399780809879303, 0.10633683204650879, -0.15603390336036682, -0.3289153277873993, -0.12077374756336212, -0.05050872266292572, -0.2080220878124237, 0.9832313656806946, 0.5417063236236572, 0.04688553512096405, 0.23259642720222473, -0.406669944524765, 0.11258251219987869, 0.3742370009422302, -0.854034423828125, 0.3083759546279907, -0.09090470522642136, 0.0025888681411743164, -0.7040609121322632, 0.3238726854324341, -0.904613733291626, -0.396487832069397, -0.6729185581207275, 0.8754828572273254, 0.2733435332775116, 0.2239121049642563, -0.2569853663444519, -0.10250057280063629, -0.17218856513500214, -0.28971365094184875, -0.07550176233053207, 0.19745048880577087, 0.3487645089626312, -0.06657911837100983, 0.11057567596435547, -0.6340450048446655, -0.5072210431098938, 1.0490740537643433, -1.1821086406707764, -0.07814428210258484, 0.49051210284233093, 0.41144096851348877, -0.7690240144729614, -0.0969967246055603, 0.26812857389450073, 0.7607074975967407, -0.4730786383152008, -0.1019342690706253, 0.3288653790950775, -0.17185042798519135, -0.37591737508773804, -0.0818498432636261, -0.2280241698026657, -0.431976318359375, -0.6011949777603149, -0.081000417470932, 0.05710218474268913, -0.5888512134552002, -0.27040237188339233, -0.09410543739795685, -0.09438524395227432, 0.2774193584918976, -0.13452762365341187, 0.09891848266124725, -0.10804782807826996, 0.31563979387283325, 0.08834736794233322, 0.6182258129119873, -1.0699074268341064, 0.19392147660255432, 0.1249566376209259, -0.03885522112250328, 0.06492863595485687, -0.3765663206577301, 0.13749511539936066, -0.025449424982070923, -0.14210207760334015, -0.07990968972444534, -0.11793680489063263, -0.20950539410114288, 0.13689403235912323, 0.0765090212225914, 0.19039148092269897, -0.3266335427761078, -0.25460636615753174, -0.03278942406177521, -0.7402831315994263, 0.09475279599428177, 0.4564286470413208, 0.4215022921562195, 0.11450295150279999, 0.34057459235191345, -0.37199896574020386, 0.006156213581562042, -0.02039993181824684, -0.2536369264125824, -0.2455439269542694, 0.23188091814517975, -0.3103940188884735, -0.7183172702789307, 0.33332914113998413, 0.4115520715713501, -0.1779150366783142, -0.5101771950721741, -0.2670041024684906, -0.34715062379837036, -0.062377721071243286, 0.3709692656993866, 0.19747109711170197, -1.0509971380233765, -0.6586863994598389, 0.6039122343063354, -0.1314733922481537, 0.06489352881908417, 0.32325994968414307, 0.5423303842544556, -0.8884979486465454, 0.18546505272388458, 0.450029194355011, -0.3698651194572449, -0.5519534945487976, -0.0042878687381744385, -1.0416784286499023, 0.20571523904800415, -0.16195690631866455, -0.13058041036128998, 0.3348664343357086, 0.4553835391998291, -0.35895952582359314, 0.1864907294511795, 0.28856760263442993, 0.16451865434646606, 0.26384738087654114, 0.3883886933326721, -0.012519650161266327, 0.3990037739276886, 0.6010568737983704, 0.5455867052078247, 0.11129451543092728, -0.24986901879310608, 2.0261178016662598, -0.1749269664287567, 0.7393905520439148, -0.6417619585990906, 0.1449599266052246, -0.21802067756652832, 0.696697473526001, 0.5523356795310974, -0.15623241662979126, -0.009038425981998444, 0.3495602309703827, -0.3720955550670624, 0.5204518437385559, 0.28594350814819336, 0.2464143931865692, 0.16423606872558594, 0.32487571239471436, 0.014574158936738968, 0.13256454467773438, 0.24534785747528076, 0.38643068075180054, 0.11267995089292526, 0.057857513427734375, 0.15267109870910645, 0.07649043947458267, -0.04618707299232483, -0.3123261332511902, 0.34701263904571533, 0.05194362998008728, -0.4584079384803772, -0.2529067099094391, -0.5631799697875977, 1.1526687145233154, -0.02309446781873703, -0.20064835250377655, -0.015126427635550499, -0.32415083050727844, -0.6441162824630737, -0.20999976992607117, 0.03671515733003616, 0.516506016254425, 0.2965751588344574, 0.21462169289588928, -0.24361062049865723, 0.33285820484161377, 0.314866304397583, -0.03787408769130707, -0.13196052610874176, 1.0063681602478027, -0.14105959236621857, 0.040885187685489655, -0.465596467256546, 0.3493189811706543, 0.5474334359169006, 0.6519780158996582, -0.3633701205253601, -0.5930523872375488, -0.8881128430366516, 0.2488826960325241, -0.5445129871368408, 0.9244774580001831, -0.11134934425354004, -0.544418454170227, 0.49819958209991455, -0.7000152468681335, -0.10551378130912781, 0.4313863217830658, 0.5186067223548889, -0.13389557600021362, -0.15162694454193115, -0.035525161772966385, 0.06885751336812973, 0.16053976118564606, 0.16528616845607758, -0.47125688195228577, 0.0293824914842844, 0.8085377216339111, 1.0395281314849854, -0.03292791172862053, 0.7322969436645508, -0.3344978094100952, -0.6630430817604065, -0.48999151587486267, -0.025532938539981842, 0.020389556884765625, 1.063123106956482, -1.5241590738296509, -0.6167834997177124, 1.3854142427444458, -0.8194777965545654, -0.006837934255599976, 0.8279674053192139, -0.23694464564323425, 0.44963008165359497, -0.2753618359565735, -0.5069367289543152, -0.4227251708507538, 0.5513660907745361, -0.8590245246887207, -0.2630205750465393, -0.12819325923919678, 0.20290154218673706, -2.140383243560791, 0.10475160926580429, -0.331283837556839, -0.557103157043457, 0.34775111079216003, -0.009290516376495361, 0.22063449025154114, 0.07995831221342087, -0.21229422092437744, -0.07905711978673935, -0.094730444252491, 0.21018226444721222, -0.1793908178806305, 0.26959437131881714, -0.4621502757072449, 0.4394351840019226, -0.5388815402984619, -0.32737940549850464, 0.0340985469520092, 0.4622047245502472, 0.12407336384057999, 0.2671564817428589, 0.5503677725791931, -0.026465125381946564, -0.8377951979637146, -0.23699288070201874, 0.2087889164686203, -0.7638313174247742, 0.26252102851867676, -0.18837887048721313, 0.0882798433303833, -0.039212457835674286, 0.2528650462627411, 0.35223865509033203, 0.07620975375175476, 0.023625928908586502, -0.018529130145907402, -0.8576803803443909, -0.3093244433403015, -0.03747260197997093, 0.28316789865493774, 0.6337483525276184, 0.15292681753635406, -0.10567024350166321, -0.1113671213388443, -0.1122347041964531, -0.1637568473815918, 0.25682398676872253, -0.6130843162536621, -0.036881618201732635, 0.306519478559494, 0.24969741702079773, 0.02888701856136322, 0.062370676547288895, -0.32862064242362976, -0.026599295437335968, -0.616278350353241, 0.1860179752111435, 0.05775371193885803, 0.019804392009973526, 0.010371759533882141, -0.2653030753135681, 0.4882490634918213, -0.02435573935508728, -0.06381768733263016, 0.5881010890007019, -0.8867501020431519, -0.8484491109848022, -0.5464807152748108, -0.2846934497356415, -0.3882216811180115, -0.10469070076942444, -0.6672641634941101, -0.41688108444213867, -0.1549680233001709, 0.34740138053894043, 0.23279714584350586, 0.0983077883720398, -0.27022886276245117, 0.3287019729614258, -0.11831728368997574, -0.320865273475647, -0.43665775656700134, 0.4207013249397278, -0.44228488206863403, -0.8492830395698547, -1.003303050994873, -0.14112016558647156, -0.3304101824760437, 0.209624782204628, 0.43323931097984314, 0.4200737774372101, 0.22656399011611938, 0.6336583495140076, -0.4028284549713135, 0.23309390246868134, -0.3299171030521393, 0.08548174798488617, 0.04380349814891815, 0.6929132342338562, -0.4287937581539154, 0.6067816019058228, 0.4432491660118103, -0.17456313967704773, 0.03112895041704178, 0.5434638261795044, 0.6626320481300354, 0.06292691826820374, -0.07513435930013657, -0.12315517663955688, 0.18106664717197418, 0.3182564973831177, 0.7358231544494629, 0.10026507079601288, -0.20939406752586365, 0.23467200994491577, -0.32365286350250244, 0.40685805678367615, -0.6634763479232788, -0.1308472454547882, -0.2146185040473938, 0.13844089210033417, -0.33917516469955444, -0.08012080937623978, -0.6640334129333496, 0.23918893933296204, -0.08911449462175369, -0.12212570756673813, -0.12705010175704956, 0.623261570930481, 0.16427379846572876, -0.8889671564102173, 0.18267178535461426, 0.19229766726493835, -0.8472200632095337, -0.011681046336889267, -0.3545877933502197, 0.16896922886371613, -0.3098375201225281, 0.25164303183555603, -0.4265620708465576, -0.1837165802717209, 0.06965453922748566, -0.09131467342376709, -0.20902344584465027, 0.42033958435058594, 0.3393080234527588, 0.5338594913482666, -0.6017694473266602, -0.2407529056072235, 0.2715449333190918, -0.25882911682128906, -0.10649436712265015, 0.13145965337753296, 0.2045527845621109, -0.38231348991394043, 0.17083239555358887, 0.20519959926605225, -1.1389423608779907, -0.6657184362411499, -0.5221261382102966, -0.25597724318504333, 0.003588549792766571, 0.06836012750864029, 0.4511655569076538, -0.21909375488758087, -0.22543461620807648, -0.4079989790916443, -0.31340929865837097, 0.08719771355390549, 0.22057758271694183, 0.3648149371147156, -0.09993533045053482, 0.03875627741217613, 0.4679565727710724, -0.24009662866592407, 0.16160263121128082, 0.20931199193000793, 0.2262687385082245, -0.5933244824409485, 0.4132431447505951, -0.2088564783334732, 0.8993890285491943, -0.006716256029903889, 0.28182315826416016, 0.0053584459237754345, -0.23628830909729004, 0.20955024659633636, 0.162777379155159, 0.0010323673486709595, -0.1338760405778885, 0.1380823850631714, -0.4298745393753052, 0.5911465883255005, -0.0217166468501091, 0.8254718780517578, -0.7002403140068054, -0.3856658339500427, -0.486555278301239, -0.27633583545684814, 0.22688177227973938, 0.12775331735610962, -0.2598212659358978, 0.515864372253418, -0.6544967889785767, 1.53041243553161

### Using hardware acceleration (GPU)

Use the parameter `device` to switch from CPU (default) to a GPU to speed up the processing, for example:

```python
from estnltk_neural.taggers import BertTagger
bert_tagger = BertTagger(device='cuda')  # use GPU
```

Note that this requires that you have the corresponding hardware available. By default, no hardware acceleration is used. 
For other possible `device` values, please consult [pytorch device documentation](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch.device).

### BERT layers

There are two versions of BERT models:

   * The BASE model - number of transformer blocks: 12, Hidden layer size: 768
   * The LARGE model - number of transformer blocks: 24, Hidden layer size: 1024

Usually, just using the base model is good enough. And BertTagger's [default model](https://huggingface.co/tartuNLP/EstBERT#) is also a base model.

BERT base model uses 12 layers and BERT large model 24 of transformer encoders, we can use each of these layers as our embeddings. 
[According to creators of BERT](https://arxiv.org/pdf/1810.04805.pdf), it is best to concatenate the last 4 layers together and use as embeddings. 
This gives an embedding vector of size 3072 for each token.
We have made the concatenation of last 4 layers also the default setting of BertTagger. 

If we still want to change the layers, we need to initialize BertTagger with updated `bert_layers` parameter:
```python
bert_tagger = BertTagger(bert_layers=[-3,-2,-1])
```
This gives us the last three layers from the model.

Let's try it out. 
We have to change the name of the output layer as well, because we already have `bert_embeddings` layer attached to our Text object.

In [7]:
bert_tagger_3 = BertTagger(bert_layers=[-3, -2, -1], output_layer='bert_embeddings_3')

Some weights of BertModel were not initialized from the model checkpoint at C:\Programmid\Miniconda3\envs\py312_devel\Lib\site-packages\estnltk\estnltk_resources\estbert\model_hf_tartunlp_2022-03-10\ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [8]:
bert_tagger_3.tag(text)

Text(text='Aga mulle tundub, et kogu maailm ootab muusikamaailmalt midagi erutavalt uut minimalismi kõrvale.')

In [9]:
text.bert_embeddings_3

Layer(name='bert_embeddings_3', attributes=('token', 'bert_embedding'), spans=SL[Span('Aga', [{'token': 'aga', 'bert_embedding': [0.26252102851867676, -0.18837887048721313, 0.0882798433303833, -0.039212457835674286, 0.2528650462627411, 0.35223865509033203, 0.07620975375175476, 0.023625928908586502, -0.018529130145907402, -0.8576803803443909, -0.3093244433403015, -0.03747260197997093, 0.28316789865493774, 0.6337483525276184, 0.15292681753635406, -0.10567024350166321, -0.1113671213388443, -0.1122347041964531, -0.1637568473815918, 0.25682398676872253, -0.6130843162536621, -0.036881618201732635, 0.306519478559494, 0.24969741702079773, 0.02888701856136322, 0.062370676547288895, -0.32862064242362976, -0.026599295437335968, -0.616278350353241, 0.1860179752111435, 0.05775371193885803, 0.019804392009973526, 0.010371759533882141, -0.2653030753135681, 0.4882490634918213, -0.02435573935508728, -0.06381768733263016, 0.5881010890007019, -0.8867501020431519, -0.8484491109848022, -0.5464807152748108, -0.2846934497356415, -0.3882216811180115, -0.10469070076942444, -0.6672641634941101, -0.41688108444213867, -0.1549680233001709, 0.34740138053894043, 0.23279714584350586, 0.0983077883720398, -0.27022886276245117, 0.3287019729614258, -0.11831728368997574, -0.320865273475647, -0.43665775656700134, 0.4207013249397278, -0.44228488206863403, -0.8492830395698547, -1.003303050994873, -0.14112016558647156, -0.3304101824760437, 0.209624782204628, 0.43323931097984314, 0.4200737774372101, 0.22656399011611938, 0.6336583495140076, -0.4028284549713135, 0.23309390246868134, -0.3299171030521393, 0.08548174798488617, 0.04380349814891815, 0.6929132342338562, -0.4287937581539154, 0.6067816019058228, 0.4432491660118103, -0.17456313967704773, 0.03112895041704178, 0.5434638261795044, 0.6626320481300354, 0.06292691826820374, -0.07513435930013657, -0.12315517663955688, 0.18106664717197418, 0.3182564973831177, 0.7358231544494629, 0.10026507079601288, -0.20939406752586365, 0.23467200994491577, -0.32365286350250244, 0.40685805678367615, -0.6634763479232788, -0.1308472454547882, -0.2146185040473938, 0.13844089210033417, -0.33917516469955444, -0.08012080937623978, -0.6640334129333496, 0.23918893933296204, -0.08911449462175369, -0.12212570756673813, -0.12705010175704956, 0.623261570930481, 0.16427379846572876, -0.8889671564102173, 0.18267178535461426, 0.19229766726493835, -0.8472200632095337, -0.011681046336889267, -0.3545877933502197, 0.16896922886371613, -0.3098375201225281, 0.25164303183555603, -0.4265620708465576, -0.1837165802717209, 0.06965453922748566, -0.09131467342376709, -0.20902344584465027, 0.42033958435058594, 0.3393080234527588, 0.5338594913482666, -0.6017694473266602, -0.2407529056072235, 0.2715449333190918, -0.25882911682128906, -0.10649436712265015, 0.13145965337753296, 0.2045527845621109, -0.38231348991394043, 0.17083239555358887, 0.20519959926605225, -1.1389423608779907, -0.6657184362411499, -0.5221261382102966, -0.25597724318504333, 0.003588549792766571, 0.06836012750864029, 0.4511655569076538, -0.21909375488758087, -0.22543461620807648, -0.4079989790916443, -0.31340929865837097, 0.08719771355390549, 0.22057758271694183, 0.3648149371147156, -0.09993533045053482, 0.03875627741217613, 0.4679565727710724, -0.24009662866592407, 0.16160263121128082, 0.20931199193000793, 0.2262687385082245, -0.5933244824409485, 0.4132431447505951, -0.2088564783334732, 0.8993890285491943, -0.006716256029903889, 0.28182315826416016, 0.0053584459237754345, -0.23628830909729004, 0.20955024659633636, 0.162777379155159, 0.0010323673486709595, -0.1338760405778885, 0.1380823850631714, -0.4298745393753052, 0.5911465883255005, -0.0217166468501091, 0.8254718780517578, -0.7002403140068054, -0.3856658339500427, -0.486555278301239, -0.27633583545684814, 0.22688177227973938, 0.12775331735610962, -0.2598212659358978, 0.515864372253418, -0.6544967889785767, 1.5304124355316162, -0.22837865352630615, 0.33682170510292053, -0.13965794444084167, -0.043725937604904175, -0.07619999349117279, 0.35802188515663147, 0.18693113327026367, -0.4378308355808258, 0.07172173261642456, -0.5409741997718811, 0.8780335187911987, -0.2239314317703247, -1.1160858869552612, -0.2940172553062439, -0.31024253368377686, -0.44835788011550903, 0.931261420249939, 0.03691379725933075, -0.8168560862541199, 0.22351714968681335, 0.5396934151649475, 0.11739061772823334, -0.5327320098876953, -0.15645676851272583, 0.6304412484169006, -0.10114268958568573, -0.01482172030955553, 0.05992276594042778, -0.4067418575286865, 0.3542864918708801, -0.6994239091873169, -0.08127535879611969, 0.5046461224555969, 0.0579390823841095, 0.30300235748291016, 0.8241091966629028, 0.07717292010784149, 1.2235257625579834, -0.2277052104473114, -0.1413431465625763, 0.1222643107175827, -0.08829690515995026, 0.6072344183921814, 0.2163674235343933, 0.08895440399646759, -0.7142622470855713, -0.17385174334049225, 4.09896183013916, -0.2226056456565857, -0.2454948127269745, -0.06006298214197159, 0.021037284284830093, 0.3234318196773529, 0.3534020185470581, -0.33721059560775757, -0.22217363119125366, 0.015229795128107071, -0.26476383209228516, 0.1456853747367859, -0.1504758596420288, 0.15885034203529358, 1.5051323175430298, 0.1418483555316925, 0.2667511999607086, 0.017063681036233902, 0.09383247047662735, 0.5992174744606018, 0.18583455681800842, -0.2230362743139267, 0.5877252221107483, -0.7496399879455566, 0.12875044345855713, 0.1567724049091339, 0.44821205735206604, -0.2639455199241638, -0.18925173580646515, 0.7182696461677551, -0.013695165514945984, 0.1702834814786911, 0.02071528136730194, -0.4657093286514282, 0.06447569280862808, 0.2710839807987213, 0.18501299619674683, 0.2561183571815491, -0.1795738935470581, -0.20540234446525574, 0.7110123038291931, 2.1888670921325684, 0.015084557235240936, 0.19199255108833313, -2.2571516036987305, -0.43884938955307007, -0.18721790611743927, 0.5126407742500305, 0.3052518665790558, 0.11772479116916656, 0.20451883971691132, -0.3258182108402252, 0.8961243629455566, -0.0007548108696937561, -0.8562260866165161, 0.01048801839351654, 0.3781293034553528, 0.4714853763580322, 0.35471346974372864, -0.3268466889858246, -0.2687625288963318, -0.15432648360729218, -0.3373326361179352, 0.10795950889587402, -0.12160827219486237, 0.4020918607711792, -0.036073826253414154, -0.030198674649000168, 0.6254768967628479, 0.5351703763008118, 0.10108789056539536, -0.38237103819847107, 0.31452345848083496, 0.8287822604179382, 0.1088247299194336, -0.016469281166791916, -0.2830285429954529, -0.13813069462776184, 0.09281527251005173, -0.2960888743400574, -1.0838558673858643, -0.47351664304733276, 0.2731683850288391, 0.15247002243995667, -0.030882354825735092, -0.13240069150924683, -0.012697625905275345, 0.12607279419898987, 0.46139243245124817, -0.32520732283592224, -0.5904642343521118, 0.5128124952316284, -0.34588655829429626, -0.11800847947597504, -0.9795131683349609, 0.46141430735588074, 0.018474005162715912, 0.00028152763843536377, -0.3301173448562622, 0.0053450800478458405, 0.7717322707176208, -0.4676326513290405, -0.3368135392665863, -0.02552393078804016, -0.10207551717758179, -0.014119427651166916, -0.1480540931224823, 0.19482101500034332, 0.07174110412597656, -0.18743756413459778, 0.5325311422348022, -0.7188200950622559, -0.0006840601563453674, 0.1527518332004547, 0.08663870394229889, -0.3946911096572876, 0.11396586149930954, -0.751640796661377, -0.41565245389938354, 0.1022648811340332, -0.4201492369174957, -0.48733755946159363, 0.059990815818309784, -0.3474463224411011, -0.014060511253774166, 0.5388566851615906, 0.7377955317497253, 0.2806963324546814, 0.10308009386062622, 0.17235468327999115, 0.19580703973770142, -0.011824585497379303, -0.2384144365787506, 0.21435269713401794, 0.0017718570306897163, 0.2526172995567322, -1.0778543949127197, -0.4217608869075775, 0.47306564450263977, -0.6130214929580688, 0.13343407213687897, -0.4204481840133667, 0.18860407173633575, 0.06143999099731445, 0.06875255703926086, 0.34947115182876587, -0.24848714470863342, -0.09384196996688843, 0.276290625333786, 0.3462038040161133, -0.4909754991531372, -0.6197444796562195, 1.0996580123901367, 0.9714168310165405, -0.20594680309295654, 0.24303680658340454, 0.13465039432048798, 0.08180542290210724, 0.13833391666412354, 0.31195613741874695, 0.354388564825058, 0.131188303232193, -0.09608916938304901, 0.24018993973731995, -0.32808390259742737, -0.21917186677455902, 0.16913175582885742, -0.2919776141643524, 0.26331424713134766, -6.5713934898376465, 0.08070827275514603, 0.08160229027271271, -0.5075055360794067, -0.0073128268122673035, 0.06512545049190521, -0.38792693614959717, -0.6318274140357971, -0.05460484325885773, 0.24578291177749634, 0.0028850771486759186, 0.6634865999221802, 0.6661384701728821, -0.058746568858623505, 0.04535912349820137, 0.0779486745595932, -0.13889560103416443, 0.35448598861694336, -0.29875466227531433, -0.2486722767353058, 0.10609210282564163, -0.034147389233112335, 0.07729858160018921, 0.13728652894496918, -0.12570050358772278, 0.06164463236927986, 0.7076054215431213, -0.022754894569516182, 0.9211748242378235, -0.6111160516738892, 0.033924415707588196, -0.16232016682624817, -0.05512639507651329, 0.4084787368774414, -0.0957408994436264, 0.317139208316803, 0.06239040195941925, -0.11441542953252792, -0.2129429131746292, 0.29609060287475586, 0.4618069529533386, 0.010156258940696716, 0.4133608937263489, -0.5136608481407166, -0.21227477490901947, 0.5121234655380249, 0.09353642165660858, -0.5809820890426636, -0.3551700711250305, 0.026969164609909058, -0.3814811110496521, 0.9287693500518799, -0.12635132670402527, -0.5939188599586487, 0.7620764374732971, -0.7391729354858398, -0.1609681099653244, 1.1461608409881592, 0.12827280163764954, -0.3602921962738037, -0.001131722703576088, 0.9328794479370117, 0.058008141815662384, 0.3010392189025879, 0.06803780794143677, 0.3060428500175476, 0.9083128571510315, 0.1072787493467331, 0.6767133474349976, -0.10762642323970795, 0.16782823204994202, 0.005530699156224728, -8.965089797973633, 0.5027081966400146, 0.07625086605548859, -0.41969311237335205, 1.3775634765625, -0.17847010493278503, -0.11600309610366821, 0.19388602674007416, -0.34028640389442444, 0.10065405070781708, -0.018097976222634315, 0.266117125749588, -0.5312155485153198, 0.21404029428958893, -0.3852240741252899, 0.14507025480270386, -0.4541538655757904, -0.4617904722690582, -0.34777259826660156, 0.22979408502578735, -0.24540266394615173, -0.10499770194292068, -0.12157388031482697, -0.06684144586324692, -0.24158689379692078, -0.8069648742675781, 0.9125158786773682, 0.42435914278030396, -0.11696165800094604, 0.5839334726333618, -0.8511940836906433, 0.02242671325802803, 0.08825772255659103, 0.27163687348365784, -0.08734861016273499, -0.3164156675338745, -0.01168624684214592, -0.15185469388961792, -0.23652473092079163, 0.9505935311317444, 0.5779855251312256, 0.013484425842761993, 0.15989193320274353, -0.03979296237230301, 0.05136166512966156, 0.19135203957557678, -0.6357276439666748, 0.24306675791740417, -0.12746740877628326, -0.030288975685834885, -0.5488351583480835, 0.5009792447090149, -0.6617299318313599, -0.06120127812027931, -0.5031461119651794, 0.6748380064964294, 0.3016848862171173, 0.41694125533103943, 0.011965435929596424, -0.07558999955654144, -0.2080076038837433, 0.006782174110412598, -0.06308692693710327, -0.03238235414028168, 0.028232969343662262, 0.22868730127811432, -0.09358423948287964, -0.5533267259597778, -0.3469441533088684, 0.9151738882064819, -0.9865756034851074, -0.004939600825309753, 0.22433584928512573, 0.39413347840309143, -0.3504471182823181, 0.096829853951931, 0.15972405672073364, 0.7248253226280212, -0.41353631019592285, -0.2681100368499756, 0.4033089280128479, -0.19383862614631653, -0.5063155889511108, -0.24946340918540955, 0.008700771257281303, -0.36578086018562317, -0.6802180409431458, 0.16138647496700287, 0.08246500045061111, -0.6330788135528564, -0.18338444828987122, -0.2448541224002838, -0.030422542244195938, 0.09164449572563171, -0.14556984603405, -0.10855721682310104, -0.12336686253547668, 0.2937735319137573, 0.2959841191768646, 0.6376309394836426, -0.9093179106712341, 0.3020213842391968, -0.01990409940481186, -0.10490547120571136, -0.2579965591430664, -0.12253429740667343, 0.036318957805633545, 0.0346418097615242, -0.15951955318450928, -0.14072853326797485, -0.22907131910324097, -0.11902019381523132, 0.15677455067634583, -0.1334463506937027, 0.13195815682411194, -0.16213351488113403, -0.26223045587539673, -0.1893286257982254, -0.6807595491409302, 0.155208021402359, 0.49953460693359375, 0.6491782069206238, 0.3506414592266083, 0.07249787449836731, -0.40879225730895996, 0.22054658830165863, -0.03207869827747345, -0.36519598960876465, -0.24083921313285828, 0.3667202591896057, -0.27302059531211853, -0.6040735244750977, 0.4842265844345093, 0.413452684879303, -0.10485227406024933, -0.3680720925331116, -0.22498983144760132, -0.3130730390548706, -0.28944090008735657, 0.3966488540172577, 0.07888229191303253, -0.7898049354553223, -0.3715686500072479, 0.43957796692848206, -0.1330583095550537, -0.13500027358531952, 0.2665386497974396, 0.6302371621131897, -1.0216130018234253, 0.028505738824605942, 0.30529260635375977, -0.29219314455986023, -0.41702720522880554, -0.043259844183921814, -0.8464632630348206, 0.22931388020515442, -0.0496465340256691, 0.17024944722652435, 0.3497408926486969, 0.412926584482193, -0.26030945777893066, 0.26876240968704224, 0.22129419445991516, -0.04783671349287033, 0.19910919666290283, 0.14774921536445618, -0.05082548409700394, 0.07822245359420776, 0.5278533697128296, 0.3233073055744171, 0.13578101992607117, -0.14992208778858185, 2.141068458557129, -0.1934863030910492, 0.4904189705848694, -0.7473797798156738, 0.126383438706398, -0.3433324694633484, 0.24129615724086761, 0.5390341877937317, -0.1118767186999321, 0.17459359765052795, 0.2769719362258911, -0.36554986238479614, 0.30545756220817566, -0.023364946246147156, 0.14599621295928955, -0.12183699011802673, 0.38582420349121094, -0.16338993608951569, 0.03623950481414795, 0.021185610443353653, 0.14934884011745453, 0.004503756761550903, -0.04162919148802757, -0.13645680248737335, 0.4273744523525238, -0.0608639158308506, -0.14909105002880096, 0.21366235613822937, 0.1289994716644287, -0.4536847174167633, -0.07783042639493942, -0.3676147758960724, 0.9221189022064209, 0.03824911266565323, -0.024576496332883835, 0.05547742545604706, -0.17804118990898132, -0.322131872177124, -0.15366236865520477, 0.27189016342163086, 0.4871676564216614, 0.2870596945285797, 0.5078549385070801, -0.07527513056993484, 0.07974999397993088, 0.27357017993927, -0.01891312003135681, -0.14852090179920197, 1.2935012578964233, 0.12711958587169647, 0.026932090520858765, -0.20877650380134583, 0.30770280957221985, 0.5141572952270508, 0.38966861367225647, -0.3433326482772827, -0.4803854823112488, -0.7886956334114075, 0.14393645524978638, -0.3839090168476105, 0.8639834523200989, -0.20153050124645233, -0.2874831259250641, 0.3247699737548828, -0.5781214237213135, 0.11230897903442383, 0.4874747395515442, 0.28955987095832825, -0.10490858554840088, -0.22078707814216614, -0.3252966105937958, 0.243338942527771, 0.07972344756126404, 0.1432330310344696, -0.3932999074459076, -0.061787351965904236, 0.7261312007904053, 1.0466997623443604, 0.3074125051498413, 0.6420009136199951, -0.11324429512023926, -0.28571632504463196, -0.5188828110694885, 0.2941673696041107, 0.3003212809562683, 1.2240067720413208, -1.5678049325942993, -0.41978466510772705, 1.3580125570297241, -0.6212102770805359, 0.2854478061199188, 0.7881110906600952, -0.09659874439239502, 0.3472225069999695, -0.11008939146995544, -0.49865350127220154, -0.299235999584198, 0.4708392024040222, -0.6763231158256531, -0.2600538730621338, -0.16532087326049805, 0.5210899114608765, -2.171820878982544, 0.01178818754851818, -0.05573313683271408, -0.6225244998931885, 0.3850512206554413, 0.21362483501434326, 0.12689149379730225, 0.10894010215997696, 0.004003934562206268, -0.2619161903858185, 0.0256224125623703, 0.16668294370174408, -0.058147527277469635, 0.29809731245040894, -0.420606791973114, 0.21939867734909058, -0.709952175617218, -0.4043826460838318, 0.24465127289295197, 0.34856683015823364, 0.1411317139863968, 0.15746116638183594, 0.1607007533311844, 0.08528359979391098, -0.8351074457168579, -0.18092316389083862, 0.12602484226226807, -0.6401938199996948, 0.10151522606611252, -0.3019814193248749, -0.1478852480649948, -0.05069500207901001, 0.21926537156105042, 0.31913578510284424, -0.0006265193223953247, 0.016382591798901558, -0.09855145215988159, -0.7344215512275696, -0.3279958963394165, -0.31151193380355835, 0.2911272943019867, 0.47804975509643555, 0.020560741424560547, -0.19813045859336853, -0.09252551943063736, -0.22318293154239655, -0.16703736782073975, 0.26684948801994324, -0.4222393035888672, -0.0685926228761673, 0.535681426525116, 0.024881601333618164, -0.12449900060892105, -0.0491257980465889, -0.1473287045955658, 0.011130742728710175, -0.38961905241012573, 0.2159619927406311, 0.22833457589149475, 0.1717878133058548, 0.19177764654159546, -0.296693354845047, 0.3805277943611145, 0.014626245945692062, -0.05920351296663284, 0.42420727014541626, -0.7075801491737366, -0.5812562704086304, -0.45470523834228516, -0.49637383222579956, -0.4621729850769043, -0.08022484183311462, -0.3559366762638092, -0.30519863963127136, -0.12724801898002625, 0.3524470329284668, 0.24922972917556763, 0.05703858286142349, -0.34979748725891113, 0.4035033881664276, -0.09559239447116852, -0.17776204645633698, -0.15651503205299377, 0.6718531250953674, -0.4868294298648834, -0.7175531387329102, -0.8063515424728394, -0.13363081216812134, -0.05337003618478775, 0.06267954409122467, 0.12535007297992706, 0.2578200399875641, -0.01861094869673252, 0.5644108653068542, -0.32138484716415405, 0.3392837643623352, -0.3663631081581116, 0.09441062808036804, 0.05454929918050766, 0.5807402729988098, -0.22856265306472778, 0.6224995255470276, 0.5325628519058228, -0.22957591712474823, -0.1183055192232132, 0.5434378385543823, 0.7134807109832764, 0.20468737185001373, -0.17943346500396729, -0.08592969924211502, -0.057717617601156235, 0.0033776015043258667, 0.4518958330154419, 0.19884039461612701, -0.2617024779319763, 0.10595620423555374, -0.2965148687362671, 0.00487569160759449, -0.5370727777481079, -0.1666863113641739, -0.014921223744750023, 0.1848868578672409, -0.22062425315380096, -0.0874796062707901, -0.5835380554199219, 0.1840868890285492, -0.06613484025001526, -0.058504845947027206, -0.12279875576496124, 0.6655058860778809, -0.02822209894657135, -0.5245115756988525, 0.04849757254123688, -0.0417294055223465, -0.7508838772773743, 0.15119488537311554, -0.12835372984409332, 0.24179284274578094, -0.45698535442352295, 0.04473021253943443, -0.22299543023109436, 0.06664246320724487, -0.05260484293103218, -0.29584988951683044, -0.05002178996801376, 0.6333054304122925, 0.41433659195899963, 0.4375319480895996, -0.39384230971336365, -0.25190645456314087, 0.34896767139434814, -0.22275184094905853, -0.17298439145088196, 0.21253062784671783, 0.15736167132854462, -0.36713218688964844, 0.09845083951950073, 0.21736879646778107, -0.9029994606971741, -0.3776230812072754, -0.2527529001235962, -0.15691271424293518, -0.08362757414579391, 0.02444840595126152, 0.1808478832244873, -0.2001945823431015, -0.02859821729362011, -0.29489707946777344, -0.27978232502937317, -0.24736857414245605, 0.3176144063472748, 0.3716953992843628, -0.08464415371417999, 0.06381005048751831, 0.5033937692642212, -0.22597666084766388, 0.15349774062633514, 0.166713148355484, 0.24696727097034454, -0.6523793935775757, 0.43820178508758545, -0.2352529615163803, 1.0430347919464111, 0.09639517962932587, 0.14185041189193726, 0.08152782171964645, -0.3798058331012726, 0.0541277676820755, 0.3158506155014038, -0.10816602408885956, -0.08298633992671967, 0.0540834441781044, 0.08391769230365753, 0.45450785756111145, 0.13929633796215057, 0.8135476112365723, -0.6912750601768494, -0.08224894851446152, -0.12634426355361938, -0.3983262777328491, 0.23621046543121338, 0.04111065715551376

We can also sum the embeddings. For that we need to specify the method for BertTagger. To add the embeddings, we need to set `method='add'`.

In [10]:
bert_tagger_sum = BertTagger(method='add', bert_layers=[-3, -2, -1], output_layer='bert_embeddings_add_3')
bert_tagger_sum.tag(text)
text.bert_embeddings_add_3

Some weights of BertModel were not initialized from the model checkpoint at C:\Programmid\Miniconda3\envs\py312_devel\Lib\site-packages\estnltk\estnltk_resources\estbert\model_hf_tartunlp_2022-03-10\ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Layer(name='bert_embeddings_add_3', attributes=('token', 'bert_embedding'), spans=SL[Span('Aga', [{'token': 'aga', 'bert_embedding': [0.8552049398422241, -1.0155975818634033, -0.1303907036781311, 0.31905341148376465, -0.016701310873031616, 1.7960726022720337, 0.23783941566944122, -0.06543310731649399, -0.2272588461637497, -1.6511456966400146, -1.3719263076782227, -0.1058824211359024, 0.6602128148078918, 1.3730779886245728, 0.15958577394485474, -0.2911289632320404, -0.36061668395996094, 0.1076352596282959, 0.2504023313522339, 1.257671594619751, -1.047726035118103, -0.39694416522979736, 1.6392579078674316, 0.4097440242767334, -0.694101870059967, -0.28422069549560547, -0.8413348197937012, -0.5645983815193176, -0.9391746520996094, 1.0735647678375244, 0.7718902230262756, -0.24353991448879242, 0.5385555624961853, -1.3906173706054688, 1.3981138467788696, 0.14340750873088837, 0.16078169643878937, 0.6886191368103027, -2.4860198497772217, -2.5255560874938965, -1.2040355205535889, -2.295318365097046, -2.5844945907592773, -0.33396005630493164, -1.8881622552871704, -1.6158015727996826, -0.20586219429969788, 0.9640374183654785, 0.4705023765563965, -0.13977965712547302, -1.4203239679336548, 1.48427414894104, -0.21186958253383636, -1.1731171607971191, -0.650092363357544, 2.1829586029052734, -1.6186476945877075, -2.994588613510132, -3.6925578117370605, -1.0784162282943726, -0.2390507161617279, 0.476875364780426, 0.36450302600860596, 1.2307164669036865, 0.6120345592498779, 1.6989524364471436, -0.9162051677703857, 0.034210801124572754, -1.3644691705703735, -0.23332332074642181, -0.5294979810714722, 2.394296646118164, -0.6777440309524536, 2.126577615737915, 1.644993543624878, -0.30916672945022583, -0.7753923535346985, 1.7795190811157227, 2.3901655673980713, -0.008941173553466797, -0.7784063816070557, -0.3772885799407959, 1.6534693241119385, 0.44871556758880615, 1.2039625644683838, 0.4164354205131531, -0.9288957118988037, 0.45370739698410034, -2.3259999752044678, -0.2837386131286621, -2.829153537750244, -0.23881343007087708, -0.5972552299499512, 0.6608551740646362, -0.6247768402099609, -0.7395797967910767, -2.97977352142334, 0.18813499808311462, -0.1053755134344101, 0.5605081915855408, 0.13550643622875214, 2.2892680168151855, 0.1282976269721985, -1.7639641761779785, 0.3084242045879364, -0.3765771985054016, -2.5961227416992188, 0.6300814747810364, -0.7658642530441284, 0.5648773908615112, -1.6034462451934814, 0.06939256191253662, -0.2001553177833557, 0.0037066638469696045, -0.5415647029876709, -0.39019057154655457, -0.2376677691936493, 1.8645061254501343, 0.8841013312339783, 1.5101981163024902, -1.7810922861099243, -0.9111465215682983, 1.3452489376068115, -0.44933050870895386, -0.8245233297348022, -0.1002839207649231, 0.25013360381126404, -0.902146577835083, 0.20124919712543488, 1.047647476196289, -3.340603828430176, -1.875772476196289, -0.8490158319473267, -0.6495343446731567, -0.04954787343740463, -0.49986934661865234, 0.40035876631736755, -1.064814567565918, -0.27423346042633057, -0.5424138903617859, -0.8444877862930298, -0.3322090804576874, 0.4252493977546692, 0.6171732544898987, -0.38041335344314575, 0.2797795534133911, 1.9307888746261597, -0.7742639183998108, 0.4590548276901245, 1.2459216117858887, 1.3067378997802734, -2.1255745887756348, 1.6584141254425049, -1.5267819166183472, 3.6485273838043213, 0.3929559588432312, 0.49440377950668335, -0.12349813431501389, -1.2647826671600342, -0.10711127519607544, 1.0811541080474854, -0.5748851299285889, -0.9573409557342529, 1.2412996292114258, -0.5663187503814697, 2.001790761947632, 0.5420629978179932, 2.482542037963867, -2.426328182220459, -1.3131945133209229, -0.8693664073944092, -0.7982568144798279, 0.49929410219192505, -0.03190813958644867, -1.5736454725265503, 2.2205376625061035, -1.6874032020568848, 5.164198875427246, -1.1048166751861572, 2.305093765258789, -0.31399813294410706, 0.462026983499527, -1.2462999820709229, 1.172602653503418, 1.6156988143920898, -0.7275875806808472, 0.20576488971710205, -1.5397077798843384, 3.2427096366882324, -1.1509993076324463, -3.7945141792297363, -1.1335468292236328, -1.3343737125396729, -0.7093391418457031, 3.8722848892211914, 0.8149458765983582, -3.5146663188934326, 0.8615725636482239, 0.187788188457489, 0.6971826553344727, -2.172330856323242, -0.6643398404121399, 1.9537005424499512, -0.903718113899231, 0.1374717801809311, 0.3575092852115631, -1.2116146087646484, 1.005049228668213, -2.326914072036743, 0.8106093406677246, 1.940510869026184, -0.04116407036781311, 1.0144777297973633, 2.256807804107666, 0.9421963095664978, 3.8640856742858887, -0.5405538082122803, -0.309317022562027, 0.9499503374099731, 0.4355652332305908, 2.937676429748535, 0.3450435996055603, 0.6396819353103638, -1.2204643487930298, 0.07442301511764526, 15.752190589904785, -0.7644069194793701, -0.42065271735191345, -0.8984553813934326, 0.31472843885421753, 0.4091174900531769, 1.8907568454742432, -1.1428767442703247, -1.191124439239502, 0.6364033222198486, -1.5656704902648926, 0.5388782024383545, -0.7494259476661682, 2.1691644191741943, 3.493652820587158, -0.41735392808914185, 0.7252433896064758, -0.05556406080722809, 0.056240834295749664, 0.22320306301116943, 0.42779073119163513, -0.3744812309741974, 1.9476184844970703, -2.1179375648498535, 0.29831308126449585, 0.759462296962738, 1.490837812423706, -1.105006456375122, -0.07883603870868683, 2.7856359481811523, -0.7337881922721863, 0.16103139519691467, 0.9632206559181213, -0.5103569030761719, 0.8228005170822144, 0.07699045538902283, 0.4044577479362488, 0.43658924102783203, -0.7310024499893188, -0.4904715418815613, 3.226813793182373, 7.9558610916137695, -1.020629644393921, 0.07196526974439621, -7.126242637634277, -1.4177535772323608, -0.7556440830230713, 2.0510501861572266, 1.004023790359497, -0.3604125380516052, 0.4101760685443878, -1.221045970916748, 0.6263278722763062, -0.36023056507110596, -2.1286513805389404, 0.5494581460952759, 1.8291921615600586, 1.818123698234558, 2.303093433380127, -0.12940198183059692, -1.277530550956726, -0.14507071673870087, -1.0305047035217285, -0.26693812012672424, -1.004920244216919, 1.4167979955673218, -0.09542995691299438, -0.20066756010055542, 1.1619113683700562, 1.1474462747573853, 0.27257707715034485, -0.9447979927062988, -0.23758530616760254, 2.9678773880004883, 0.3935551047325134, 0.6591106653213501, -0.18186989426612854, -0.137405663728714, -0.19641894102096558, -0.35425180196762085, -2.642503261566162, -1.5531563758850098, 1.1761205196380615, 0.0014476180076599121, 0.023523490875959396, -0.8770923018455505, -0.40813344717025757, 0.29640763998031616, -0.5110055804252625, -2.6062073707580566, -1.128597617149353, 1.6924172639846802, -1.1207737922668457, -1.5362379550933838, -2.4877572059631348, 0.5683497786521912, 0.6297143697738647, -0.41736626625061035, -1.4591107368469238, 0.43231910467147827, 2.2832226753234863, -0.6569114923477173, -1.7874014377593994, -0.2121969759464264, -0.23202411830425262, 0.07217024266719818, -0.839850664138794, 0.508573591709137, -0.752079427242279, -0.10991787910461426, 1.713362693786621, -2.642319917678833, -0.8632217645645142, 0.31501051783561707, -0.08143357187509537, -1.6427875757217407, -0.15689828991889954, -1.6905728578567505, -1.6638014316558838, -2.1096622943878174, -0.5625022649765015, -1.9134185314178467, 0.12992236018180847, -1.112295389175415, -0.43427717685699463, 1.9715443849563599, 2.443070411682129, 0.05865435302257538, -0.4837825298309326, 0.7785762548446655, 0.9036924839019775, 0.2826870381832123, -0.20348109304904938, 0.05821216106414795, -0.5442628860473633, 0.324181467294693, -4.329375267028809, -1.4608814716339111, 0.875880241394043, -0.8415703177452087, -0.34778892993927, -1.6170552968978882, 0.15935105085372925, 0.016606450080871582, 0.2501216530799866, 1.1423921585083008, -0.5416855216026306, 0.09015673398971558, 0.03887581825256348, 0.9726724028587341, -1.819058895111084, -1.409198522567749, 3.9136366844177246, 4.190450668334961, -1.0723241567611694, 0.42471957206726074, 0.5712084770202637, 0.31710758805274963, 0.8498929738998413, 1.7384274005889893, 0.743268609046936, 0.19109880924224854, -0.17701837420463562, 1.0403677225112915, -0.04758155345916748, -0.7992848753929138, 1.6726317405700684, -0.9496938586235046, 0.5680464506149292, -17.3780460357666, -0.08174686133861542, -0.45025140047073364, -2.268078327178955, 0.27943065762519836, -0.11487478017807007, -1.208560824394226, -1.1684550046920776, 0.5702294707298279, 1.0297598838806152, 0.3563835918903351, 1.453209638595581, 2.8229596614837646, 0.7926732897758484, 0.6256923675537109, 0.5943639874458313, 0.33555638790130615, 0.38684576749801636, -1.5233111381530762, -0.04416024684906006, -0.26389506459236145, -0.5668496489524841, 0.7881386280059814, 0.0346321165561676, -0.4965885877609253, 0.9000716805458069, 3.3450756072998047, 0.31490176916122437, 3.3610167503356934, -1.4468926191329956, -0.484799861907959, -0.8947631120681763, 0.09396674484014511, 1.6443462371826172, -0.38287797570228577, 0.7270628213882446, -0.1294214129447937, 0.30076169967651367, -0.5110905170440674, -0.20569634437561035, 0.8527665138244629, 0.4825703799724579, 2.111562728881836, -1.0845491886138916, -1.0132784843444824, 0.42169079184532166, 0.38953590393066406, -2.229494571685791, -1.7829949855804443, -0.45604628324508667, 0.2954535186290741, 2.3803870677948, 0.2739182412624359, -1.992232322692871, 3.5301411151885986, -2.031641960144043, -0.12517793476581573, 3.5085256099700928, 0.07820349931716919, -1.609209656715393, -0.5791529417037964, 2.6065447330474854, -0.4798756241798401, 1.1455637216567993, 0.24722370505332947, 1.0883718729019165, 3.416301727294922, 0.4596700668334961, 2.719247341156006, -0.7485053539276123, 0.20480628311634064, 0.9187792539596558, -25.93568992614746, 0.38187527656555176, -0.7790445685386658, -0.9966616630554199, 5.066617965698242, -0.9380132555961609, 0.5945031642913818, 0.3273029923439026, -1.431102991104126, 0.7169924974441528, -0.8044986128807068, 1.0722850561141968, -0.8993695974349976, 0.3938051462173462, -1.372685432434082, 0.6432000398635864, -0.6620150804519653, -2.155329942703247, -0.5684605836868286, 0.10308429598808289, -1.4260444641113281, 0.3101568818092346, -0.4468937814235687, 0.20455628633499146, -1.009451150894165, -2.9706859588623047, 2.884763479232788, 1.2581043243408203, -0.06752020120620728, 2.888108730316162, -3.031383514404297, 0.6264306306838989, 0.06746780872344971, 0.6142776012420654, -0.4265415668487549, -1.4080734252929688, -0.7227131724357605, -0.22708746790885925, -0.977475643157959, 4.014811038970947, 1.516448736190796, -0.33168819546699524, -0.39554888010025024, -0.47491660714149475, 0.46597984433174133, 1.4786598682403564, -1.3526852130889893, 0.6187312006950378, -0.2541065216064453, -1.3824414014816284, -2.2285497188568115, 0.18002867698669434, -2.5047640800476074, 0.45855772495269775, -1.182971715927124, 1.9565554857254028, 1.2368240356445312, 1.183186411857605, -0.6259772777557373, 0.18984173238277435, -0.985464334487915, 0.3721316456794739, -0.16170141100883484, 0.8429970145225525, 0.9887992143630981, 0.7954761981964111, -1.2457019090652466, -1.9179842472076416, -1.920064926147461, 2.4473137855529785, -2.5878872871398926, -0.21590472757816315, 0.19427818059921265, -0.15624654293060303, 0.04640483856201172, 0.190092071890831, 0.6558132171630859, 1.844867467880249, -1.909822940826416, -1.3727686405181885, 1.5026252269744873, -0.6268984079360962, -2.2463326454162598, -0.050857678055763245, -0.35961487889289856, -1.4020085334777832, -2.8263773918151855, 0.5777750015258789, -0.024657592177391052, -2.754648208618164, -0.819164514541626, -0.7600294947624207, 0.45644813776016235, -0.5965050458908081, -0.2843021750450134, -1.6475125551223755, -0.0469546765089035, -0.36756399273872375, 1.3109955787658691, 1.6083276271820068, -1.7692347764968872, 1.7219526767730713, -0.03489615023136139, 0.30648499727249146, -0.8066285252571106, -0.5350372195243835, -0.2629583179950714, 0.818932056427002, 0.01602959632873535, -0.5527310371398926, -0.5922927856445312, -0.16001015901565552, -0.26611754298210144, 0.5525884032249451, -0.16199332475662231, -1.1128950119018555, -0.4749678671360016, -1.036556363105774, -1.848893404006958, 0.07215891778469086, 1.4845304489135742, 2.501437187194824, 1.840161681175232, 0.3462161421775818, -1.7597713470458984, 0.5180191397666931, 0.4997100234031677, -0.7017430663108826, -1.105011224746704, 1.3108521699905396, -1.0065592527389526, -2.089803695678711, 1.0739363431930542, 1.2875161170959473, -0.7352020740509033, -1.5545532703399658, -1.152604579925537, -1.7370976209640503, 0.013262242078781128, 1.819960594177246, -0.3672858476638794, -2.1859664916992188, -0.7584980130195618, 1.911882996559143, -0.5872899293899536, -0.2726454734802246, -0.20080667734146118, 2.5536246299743652, -3.9268603324890137, -0.835473358631134, 1.1171070337295532, -0.5901490449905396, -0.8302338719367981, -0.7781082987785339, -2.329146385192871, 1.3535034656524658, 0.45396268367767334, 0.7576618194580078, 1.197448968887329, 0.9325611591339111, -0.5943650007247925, 0.0505145788192749, 1.1101014614105225, -0.20258960127830505, -0.6174384951591492, 1.129647970199585, 0.0926348865032196, 0.4722837805747986, 2.1766324043273926, 1.2430377006530762, 0.6984738111495972, 0.13553446531295776, 8.59972095489502, 0.49141520261764526, 2.016151189804077, -2.97111177444458, -0.08248531818389893, -1.1185139417648315, 0.007051065564155579, 1.1478806734085083, -0.8214309215545654, 0.6944001913070679, -0.1571352183818817, -1.598339319229126, -0.2760131359100342, 0.03646030277013779, 0.8394750356674194, -0.6531307697296143, 1.11203932762146, -0.6220108270645142, -0.6717928647994995, -0.6208282709121704, -0.005672067403793335, -0.08117696642875671, -0.5418869256973267, -0.8666865229606628, 0.578141987323761, -0.20999793708324432, 0.22954119741916656, -0.1921488642692566, 0.6705071926116943, -2.77588152885437, -0.4046323299407959, -0.6192716956138611, 4.324591159820557, 1.1526174545288086, -0.3887728750705719, -0.10098610818386078, -0.8806823492050171, -0.6868044137954712, 0.15593338012695312, 1.2303049564361572, 2.0700883865356445, 0.5061739087104797, 1.6075899600982666, 0.014223214238882065, 0.7346529960632324, 1.5264848470687866, -0.7407999634742737, -0.06854142248630524, 4.293304920196533, 0.6856623888015747, -0.9418964385986328, 0.05795097351074219, 0.5028594136238098, 0.5677886605262756, 2.0541625022888184, -0.7862877249717712, -1.9487937688827515, -3.645446300506592, 0.9609358310699463, -1.2702908515930176, 2.6889266967773438, -0.6861351728439331, -0.45536160469055176, 0.9517232179641724, -2.13596510887146, 1.0442676544189453, 2.0066919326782227, 0.5502586364746094, -0.3835834264755249, -0.584632933139801, -0.13068078458309174, 0.7590057849884033, 0.12994584441184998, 0.10159619152545929, -1.2520859241485596, -0.058467477560043335, 1.079084873199463, 5.1487627029418945, -0.22405073046684265, 1.492834448814392, -0.5891016721725464, 0.2866519093513489, -2.0595850944519043, 0.31654462218284607, 0.9686880111694336, 4.736019611358643, -3.714048385620117, -0.6440491676330566, 3.811281681060791, -2.6664180755615234, 0.8369597792625427, 2.394505500793457, 0.3923663794994354, 0.06426805257797241, 0.5437178015708923, -2.6746034622192383, -1.0436160564422607, 1.009324073791504, -1.8388903141021729, -1.51399827003479, 0.5761089324951172, 2.1374969482421875, -9.005335807800293, 0.1483323723077774, 0.13914050161838531, -1.3223578929901123, 0.6041407585144043, 0.5231344699859619, -0.07380920648574829, 1.1671693325042725, 0.45975953340530396, -0.3733084797859192, -0.36786574125289917, -0.2925318479537964, 0.3219032287597656, 0.8111318349838257, -2.47589111328125, 0.3028194010257721, -1.7692720890045166, -1.1740132570266724, 0.709801435470581, 1.4805656671524048, 0.5488992929458618, 0.19523613154888153, 0.5250097513198853, -0.6678575873374939, -2.6735024452209473, -0.4618326723575592, -0.10966166853904724, -1.685793161392212]}]),

We can see that adding the embeddings will result to embeddings with shape (768,), but the concatenated ones larger:

In [11]:
# size of summed up embeddings
len(text.bert_embeddings_add_3[0].bert_embedding)

768

In [12]:
# size of concatenated embeddings
len(text.bert_embeddings[0].bert_embedding)

3072

We can also return all the embeddings from the layers chosen. We can see that the output is now a list containing 3 embeddings:

In [13]:
bert_tagger_all = BertTagger(method='all', bert_layers=[-3, -2, -1], output_layer='bert_embeddings_all_3')
bert_tagger_all.tag(text)
text.bert_embeddings_all_3

Some weights of BertModel were not initialized from the model checkpoint at C:\Programmid\Miniconda3\envs\py312_devel\Lib\site-packages\estnltk\estnltk_resources\estbert\model_hf_tartunlp_2022-03-10\ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Layer(name='bert_embeddings_all_3', attributes=('token', 'bert_embedding'), spans=SL[Span('Aga', [{'token': 'aga', 'bert_embedding': <class 'list'>}]),
Span('mulle', [{'token': 'mulle', 'bert_embedding': <class 'list'>}]),
Span('tundub', [{'token': 'tundub', 'bert_embedding': <class 'list'>}]),
Span(',', [{'token': ',', 'bert_embedding': <class 'list'>}]),
Span('et', [{'token': 'et', 'bert_embedding': <class 'list'>}]),
Span('kogu', [{'token': 'kogu', 'bert_embedding': <class 'list'>}]),
Span('maailm', [{'token': 'maailm', 'bert_embedding': <class 'list'>}]),
Span('ootab', [{'token': 'ootab', 'bert_embedding': <class 'list'>}]),
Span('muusika', [{'token': 'muusika', 'bert_embedding': <class 'list'>}]),
Span('maailma', [{'token': '##maailma', 'bert_embedding': <class 'list'>}]),
Span('lt', [{'token': '##lt', 'bert_embedding': <class 'list'>}]),
Span('midagi', [{'token': 'midagi', 'bert_embedding': <class 'list'>}]),
Span('eru', [{'token': 'eru', 'bert_embedding': <class 'list'>}]),
Span('tavalt', [{'token': '##tavalt', 'bert_embedding': <class 'list'>}]),
Span('uut', [{'token': 'uut', 'bert_embedding': <class 'list'>}]),
Span('minima', [{'token': 'minima', 'bert_embedding': <class 'list'>}]),
Span('lismi', [{'token': '##lismi', 'bert_embedding': <class 'list'>}]),
Span('kõrva', [{'token': 'korva', 'bert_embedding': <class 'list'>}]),
Span('le', [{'token': '##le', 'bert_embedding': <class 'list'>}]),
Span('.', [{'token': '.', 'bert_embedding': <class 'list'>}])])

### Word level embeddings

As BERT uses tokenizer that splits words into subwords, we get embeddings for those subwords and not for whole words. If we still want word-level embeddings we can _add up all the subword embeddings_ that constitute a word. It will follow the EstNLTK default tokenizer to get the separate words. 

To get the word level embeddings, we need to tell the BertTagger that we do not want token level embeddings, so we have to set `token_level=False`.

In [14]:
bert_tagger_word = BertTagger(bert_layers=[-3, -2, -1], output_layer='bert_embeddings_word', token_level=False)
bert_tagger_word.tag(text)
text.bert_embeddings_word

Some weights of BertModel were not initialized from the model checkpoint at C:\Programmid\Miniconda3\envs\py312_devel\Lib\site-packages\estnltk\estnltk_resources\estbert\model_hf_tartunlp_2022-03-10\ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Layer(name='bert_embeddings_word', attributes=('token', 'bert_embedding'), spans=SL[Span('Aga', [{'token': ['aga'], 'bert_embedding': [0.26252102851867676, -0.18837887048721313, 0.0882798433303833, -0.039212457835674286, 0.2528650462627411, 0.35223865509033203, 0.07620975375175476, 0.023625928908586502, -0.018529130145907402, -0.8576803803443909, -0.3093244433403015, -0.03747260197997093, 0.28316789865493774, 0.6337483525276184, 0.15292681753635406, -0.10567024350166321, -0.1113671213388443, -0.1122347041964531, -0.1637568473815918, 0.25682398676872253, -0.6130843162536621, -0.036881618201732635, 0.306519478559494, 0.24969741702079773, 0.02888701856136322, 0.062370676547288895, -0.32862064242362976, -0.026599295437335968, -0.616278350353241, 0.1860179752111435, 0.05775371193885803, 0.019804392009973526, 0.010371759533882141, -0.2653030753135681, 0.4882490634918213, -0.02435573935508728, -0.06381768733263016, 0.5881010890007019, -0.8867501020431519, -0.8484491109848022, -0.5464807152748108, -0.2846934497356415, -0.3882216811180115, -0.10469070076942444, -0.6672641634941101, -0.41688108444213867, -0.1549680233001709, 0.34740138053894043, 0.23279714584350586, 0.0983077883720398, -0.27022886276245117, 0.3287019729614258, -0.11831728368997574, -0.320865273475647, -0.43665775656700134, 0.4207013249397278, -0.44228488206863403, -0.8492830395698547, -1.003303050994873, -0.14112016558647156, -0.3304101824760437, 0.209624782204628, 0.43323931097984314, 0.4200737774372101, 0.22656399011611938, 0.6336583495140076, -0.4028284549713135, 0.23309390246868134, -0.3299171030521393, 0.08548174798488617, 0.04380349814891815, 0.6929132342338562, -0.4287937581539154, 0.6067816019058228, 0.4432491660118103, -0.17456313967704773, 0.03112895041704178, 0.5434638261795044, 0.6626320481300354, 0.06292691826820374, -0.07513435930013657, -0.12315517663955688, 0.18106664717197418, 0.3182564973831177, 0.7358231544494629, 0.10026507079601288, -0.20939406752586365, 0.23467200994491577, -0.32365286350250244, 0.40685805678367615, -0.6634763479232788, -0.1308472454547882, -0.2146185040473938, 0.13844089210033417, -0.33917516469955444, -0.08012080937623978, -0.6640334129333496, 0.23918893933296204, -0.08911449462175369, -0.12212570756673813, -0.12705010175704956, 0.623261570930481, 0.16427379846572876, -0.8889671564102173, 0.18267178535461426, 0.19229766726493835, -0.8472200632095337, -0.011681046336889267, -0.3545877933502197, 0.16896922886371613, -0.3098375201225281, 0.25164303183555603, -0.4265620708465576, -0.1837165802717209, 0.06965453922748566, -0.09131467342376709, -0.20902344584465027, 0.42033958435058594, 0.3393080234527588, 0.5338594913482666, -0.6017694473266602, -0.2407529056072235, 0.2715449333190918, -0.25882911682128906, -0.10649436712265015, 0.13145965337753296, 0.2045527845621109, -0.38231348991394043, 0.17083239555358887, 0.20519959926605225, -1.1389423608779907, -0.6657184362411499, -0.5221261382102966, -0.25597724318504333, 0.003588549792766571, 0.06836012750864029, 0.4511655569076538, -0.21909375488758087, -0.22543461620807648, -0.4079989790916443, -0.31340929865837097, 0.08719771355390549, 0.22057758271694183, 0.3648149371147156, -0.09993533045053482, 0.03875627741217613, 0.4679565727710724, -0.24009662866592407, 0.16160263121128082, 0.20931199193000793, 0.2262687385082245, -0.5933244824409485, 0.4132431447505951, -0.2088564783334732, 0.8993890285491943, -0.006716256029903889, 0.28182315826416016, 0.0053584459237754345, -0.23628830909729004, 0.20955024659633636, 0.162777379155159, 0.0010323673486709595, -0.1338760405778885, 0.1380823850631714, -0.4298745393753052, 0.5911465883255005, -0.0217166468501091, 0.8254718780517578, -0.7002403140068054, -0.3856658339500427, -0.486555278301239, -0.27633583545684814, 0.22688177227973938, 0.12775331735610962, -0.2598212659358978, 0.515864372253418, -0.6544967889785767, 1.5304124355316162, -0.22837865352630615, 0.33682170510292053, -0.13965794444084167, -0.043725937604904175, -0.07619999349117279, 0.35802188515663147, 0.18693113327026367, -0.4378308355808258, 0.07172173261642456, -0.5409741997718811, 0.8780335187911987, -0.2239314317703247, -1.1160858869552612, -0.2940172553062439, -0.31024253368377686, -0.44835788011550903, 0.931261420249939, 0.03691379725933075, -0.8168560862541199, 0.22351714968681335, 0.5396934151649475, 0.11739061772823334, -0.5327320098876953, -0.15645676851272583, 0.6304412484169006, -0.10114268958568573, -0.01482172030955553, 0.05992276594042778, -0.4067418575286865, 0.3542864918708801, -0.6994239091873169, -0.08127535879611969, 0.5046461224555969, 0.0579390823841095, 0.30300235748291016, 0.8241091966629028, 0.07717292010784149, 1.2235257625579834, -0.2277052104473114, -0.1413431465625763, 0.1222643107175827, -0.08829690515995026, 0.6072344183921814, 0.2163674235343933, 0.08895440399646759, -0.7142622470855713, -0.17385174334049225, 4.09896183013916, -0.2226056456565857, -0.2454948127269745, -0.06006298214197159, 0.021037284284830093, 0.3234318196773529, 0.3534020185470581, -0.33721059560775757, -0.22217363119125366, 0.015229795128107071, -0.26476383209228516, 0.1456853747367859, -0.1504758596420288, 0.15885034203529358, 1.5051323175430298, 0.1418483555316925, 0.2667511999607086, 0.017063681036233902, 0.09383247047662735, 0.5992174744606018, 0.18583455681800842, -0.2230362743139267, 0.5877252221107483, -0.7496399879455566, 0.12875044345855713, 0.1567724049091339, 0.44821205735206604, -0.2639455199241638, -0.18925173580646515, 0.7182696461677551, -0.013695165514945984, 0.1702834814786911, 0.02071528136730194, -0.4657093286514282, 0.06447569280862808, 0.2710839807987213, 0.18501299619674683, 0.2561183571815491, -0.1795738935470581, -0.20540234446525574, 0.7110123038291931, 2.1888670921325684, 0.015084557235240936, 0.19199255108833313, -2.2571516036987305, -0.43884938955307007, -0.18721790611743927, 0.5126407742500305, 0.3052518665790558, 0.11772479116916656, 0.20451883971691132, -0.3258182108402252, 0.8961243629455566, -0.0007548108696937561, -0.8562260866165161, 0.01048801839351654, 0.3781293034553528, 0.4714853763580322, 0.35471346974372864, -0.3268466889858246, -0.2687625288963318, -0.15432648360729218, -0.3373326361179352, 0.10795950889587402, -0.12160827219486237, 0.4020918607711792, -0.036073826253414154, -0.030198674649000168, 0.6254768967628479, 0.5351703763008118, 0.10108789056539536, -0.38237103819847107, 0.31452345848083496, 0.8287822604179382, 0.1088247299194336, -0.016469281166791916, -0.2830285429954529, -0.13813069462776184, 0.09281527251005173, -0.2960888743400574, -1.0838558673858643, -0.47351664304733276, 0.2731683850288391, 0.15247002243995667, -0.030882354825735092, -0.13240069150924683, -0.012697625905275345, 0.12607279419898987, 0.46139243245124817, -0.32520732283592224, -0.5904642343521118, 0.5128124952316284, -0.34588655829429626, -0.11800847947597504, -0.9795131683349609, 0.46141430735588074, 0.018474005162715912, 0.00028152763843536377, -0.3301173448562622, 0.0053450800478458405, 0.7717322707176208, -0.4676326513290405, -0.3368135392665863, -0.02552393078804016, -0.10207551717758179, -0.014119427651166916, -0.1480540931224823, 0.19482101500034332, 0.07174110412597656, -0.18743756413459778, 0.5325311422348022, -0.7188200950622559, -0.0006840601563453674, 0.1527518332004547, 0.08663870394229889, -0.3946911096572876, 0.11396586149930954, -0.751640796661377, -0.41565245389938354, 0.1022648811340332, -0.4201492369174957, -0.48733755946159363, 0.059990815818309784, -0.3474463224411011, -0.014060511253774166, 0.5388566851615906, 0.7377955317497253, 0.2806963324546814, 0.10308009386062622, 0.17235468327999115, 0.19580703973770142, -0.011824585497379303, -0.2384144365787506, 0.21435269713401794, 0.0017718570306897163, 0.2526172995567322, -1.0778543949127197, -0.4217608869075775, 0.47306564450263977, -0.6130214929580688, 0.13343407213687897, -0.4204481840133667, 0.18860407173633575, 0.06143999099731445, 0.06875255703926086, 0.34947115182876587, -0.24848714470863342, -0.09384196996688843, 0.276290625333786, 0.3462038040161133, -0.4909754991531372, -0.6197444796562195, 1.0996580123901367, 0.9714168310165405, -0.20594680309295654, 0.24303680658340454, 0.13465039432048798, 0.08180542290210724, 0.13833391666412354, 0.31195613741874695, 0.354388564825058, 0.131188303232193, -0.09608916938304901, 0.24018993973731995, -0.32808390259742737, -0.21917186677455902, 0.16913175582885742, -0.2919776141643524, 0.26331424713134766, -6.5713934898376465, 0.08070827275514603, 0.08160229027271271, -0.5075055360794067, -0.0073128268122673035, 0.06512545049190521, -0.38792693614959717, -0.6318274140357971, -0.05460484325885773, 0.24578291177749634, 0.0028850771486759186, 0.6634865999221802, 0.6661384701728821, -0.058746568858623505, 0.04535912349820137, 0.0779486745595932, -0.13889560103416443, 0.35448598861694336, -0.29875466227531433, -0.2486722767353058, 0.10609210282564163, -0.034147389233112335, 0.07729858160018921, 0.13728652894496918, -0.12570050358772278, 0.06164463236927986, 0.7076054215431213, -0.022754894569516182, 0.9211748242378235, -0.6111160516738892, 0.033924415707588196, -0.16232016682624817, -0.05512639507651329, 0.4084787368774414, -0.0957408994436264, 0.317139208316803, 0.06239040195941925, -0.11441542953252792, -0.2129429131746292, 0.29609060287475586, 0.4618069529533386, 0.010156258940696716, 0.4133608937263489, -0.5136608481407166, -0.21227477490901947, 0.5121234655380249, 0.09353642165660858, -0.5809820890426636, -0.3551700711250305, 0.026969164609909058, -0.3814811110496521, 0.9287693500518799, -0.12635132670402527, -0.5939188599586487, 0.7620764374732971, -0.7391729354858398, -0.1609681099653244, 1.1461608409881592, 0.12827280163764954, -0.3602921962738037, -0.001131722703576088, 0.9328794479370117, 0.058008141815662384, 0.3010392189025879, 0.06803780794143677, 0.3060428500175476, 0.9083128571510315, 0.1072787493467331, 0.6767133474349976, -0.10762642323970795, 0.16782823204994202, 0.005530699156224728, -8.965089797973633, 0.5027081966400146, 0.07625086605548859, -0.41969311237335205, 1.3775634765625, -0.17847010493278503, -0.11600309610366821, 0.19388602674007416, -0.34028640389442444, 0.10065405070781708, -0.018097976222634315, 0.266117125749588, -0.5312155485153198, 0.21404029428958893, -0.3852240741252899, 0.14507025480270386, -0.4541538655757904, -0.4617904722690582, -0.34777259826660156, 0.22979408502578735, -0.24540266394615173, -0.10499770194292068, -0.12157388031482697, -0.06684144586324692, -0.24158689379692078, -0.8069648742675781, 0.9125158786773682, 0.42435914278030396, -0.11696165800094604, 0.5839334726333618, -0.8511940836906433, 0.02242671325802803, 0.08825772255659103, 0.27163687348365784, -0.08734861016273499, -0.3164156675338745, -0.01168624684214592, -0.15185469388961792, -0.23652473092079163, 0.9505935311317444, 0.5779855251312256, 0.013484425842761993, 0.15989193320274353, -0.03979296237230301, 0.05136166512966156, 0.19135203957557678, -0.6357276439666748, 0.24306675791740417, -0.12746740877628326, -0.030288975685834885, -0.5488351583480835, 0.5009792447090149, -0.6617299318313599, -0.06120127812027931, -0.5031461119651794, 0.6748380064964294, 0.3016848862171173, 0.41694125533103943, 0.011965435929596424, -0.07558999955654144, -0.2080076038837433, 0.006782174110412598, -0.06308692693710327, -0.03238235414028168, 0.028232969343662262, 0.22868730127811432, -0.09358423948287964, -0.5533267259597778, -0.3469441533088684, 0.9151738882064819, -0.9865756034851074, -0.004939600825309753, 0.22433584928512573, 0.39413347840309143, -0.3504471182823181, 0.096829853951931, 0.15972405672073364, 0.7248253226280212, -0.41353631019592285, -0.2681100368499756, 0.4033089280128479, -0.19383862614631653, -0.5063155889511108, -0.24946340918540955, 0.008700771257281303, -0.36578086018562317, -0.6802180409431458, 0.16138647496700287, 0.08246500045061111, -0.6330788135528564, -0.18338444828987122, -0.2448541224002838, -0.030422542244195938, 0.09164449572563171, -0.14556984603405, -0.10855721682310104, -0.12336686253547668, 0.2937735319137573, 0.2959841191768646, 0.6376309394836426, -0.9093179106712341, 0.3020213842391968, -0.01990409940481186, -0.10490547120571136, -0.2579965591430664, -0.12253429740667343, 0.036318957805633545, 0.0346418097615242, -0.15951955318450928, -0.14072853326797485, -0.22907131910324097, -0.11902019381523132, 0.15677455067634583, -0.1334463506937027, 0.13195815682411194, -0.16213351488113403, -0.26223045587539673, -0.1893286257982254, -0.6807595491409302, 0.155208021402359, 0.49953460693359375, 0.6491782069206238, 0.3506414592266083, 0.07249787449836731, -0.40879225730895996, 0.22054658830165863, -0.03207869827747345, -0.36519598960876465, -0.24083921313285828, 0.3667202591896057, -0.27302059531211853, -0.6040735244750977, 0.4842265844345093, 0.413452684879303, -0.10485227406024933, -0.3680720925331116, -0.22498983144760132, -0.3130730390548706, -0.28944090008735657, 0.3966488540172577, 0.07888229191303253, -0.7898049354553223, -0.3715686500072479, 0.43957796692848206, -0.1330583095550537, -0.13500027358531952, 0.2665386497974396, 0.6302371621131897, -1.0216130018234253, 0.028505738824605942, 0.30529260635375977, -0.29219314455986023, -0.41702720522880554, -0.043259844183921814, -0.8464632630348206, 0.22931388020515442, -0.0496465340256691, 0.17024944722652435, 0.3497408926486969, 0.412926584482193, -0.26030945777893066, 0.26876240968704224, 0.22129419445991516, -0.04783671349287033, 0.19910919666290283, 0.14774921536445618, -0.05082548409700394, 0.07822245359420776, 0.5278533697128296, 0.3233073055744171, 0.13578101992607117, -0.14992208778858185, 2.141068458557129, -0.1934863030910492, 0.4904189705848694, -0.7473797798156738, 0.126383438706398, -0.3433324694633484, 0.24129615724086761, 0.5390341877937317, -0.1118767186999321, 0.17459359765052795, 0.2769719362258911, -0.36554986238479614, 0.30545756220817566, -0.023364946246147156, 0.14599621295928955, -0.12183699011802673, 0.38582420349121094, -0.16338993608951569, 0.03623950481414795, 0.021185610443353653, 0.14934884011745453, 0.004503756761550903, -0.04162919148802757, -0.13645680248737335, 0.4273744523525238, -0.0608639158308506, -0.14909105002880096, 0.21366235613822937, 0.1289994716644287, -0.4536847174167633, -0.07783042639493942, -0.3676147758960724, 0.9221189022064209, 0.03824911266565323, -0.024576496332883835, 0.05547742545604706, -0.17804118990898132, -0.322131872177124, -0.15366236865520477, 0.27189016342163086, 0.4871676564216614, 0.2870596945285797, 0.5078549385070801, -0.07527513056993484, 0.07974999397993088, 0.27357017993927, -0.01891312003135681, -0.14852090179920197, 1.2935012578964233, 0.12711958587169647, 0.026932090520858765, -0.20877650380134583, 0.30770280957221985, 0.5141572952270508, 0.38966861367225647, -0.3433326482772827, -0.4803854823112488, -0.7886956334114075, 0.14393645524978638, -0.3839090168476105, 0.8639834523200989, -0.20153050124645233, -0.2874831259250641, 0.3247699737548828, -0.5781214237213135, 0.11230897903442383, 0.4874747395515442, 0.28955987095832825, -0.10490858554840088, -0.22078707814216614, -0.3252966105937958, 0.243338942527771, 0.07972344756126404, 0.1432330310344696, -0.3932999074459076, -0.061787351965904236, 0.7261312007904053, 1.0466997623443604, 0.3074125051498413, 0.6420009136199951, -0.11324429512023926, -0.28571632504463196, -0.5188828110694885, 0.2941673696041107, 0.3003212809562683, 1.2240067720413208, -1.5678049325942993, -0.41978466510772705, 1.3580125570297241, -0.6212102770805359, 0.2854478061199188, 0.7881110906600952, -0.09659874439239502, 0.3472225069999695, -0.11008939146995544, -0.49865350127220154, -0.299235999584198, 0.4708392024040222, -0.6763231158256531, -0.2600538730621338, -0.16532087326049805, 0.5210899114608765, -2.171820878982544, 0.01178818754851818, -0.05573313683271408, -0.6225244998931885, 0.3850512206554413, 0.21362483501434326, 0.12689149379730225, 0.10894010215997696, 0.004003934562206268, -0.2619161903858185, 0.0256224125623703, 0.16668294370174408, -0.058147527277469635, 0.29809731245040894, -0.420606791973114, 0.21939867734909058, -0.709952175617218, -0.4043826460838318, 0.24465127289295197, 0.34856683015823364, 0.1411317139863968, 0.15746116638183594, 0.1607007533311844, 0.08528359979391098, -0.8351074457168579, -0.18092316389083862, 0.12602484226226807, -0.6401938199996948, 0.10151522606611252, -0.3019814193248749, -0.1478852480649948, -0.05069500207901001, 0.21926537156105042, 0.31913578510284424, -0.0006265193223953247, 0.016382591798901558, -0.09855145215988159, -0.7344215512275696, -0.3279958963394165, -0.31151193380355835, 0.2911272943019867, 0.47804975509643555, 0.020560741424560547, -0.19813045859336853, -0.09252551943063736, -0.22318293154239655, -0.16703736782073975, 0.26684948801994324, -0.4222393035888672, -0.0685926228761673, 0.535681426525116, 0.024881601333618164, -0.12449900060892105, -0.0491257980465889, -0.1473287045955658, 0.011130742728710175, -0.38961905241012573, 0.2159619927406311, 0.22833457589149475, 0.1717878133058548, 0.19177764654159546, -0.296693354845047, 0.3805277943611145, 0.014626245945692062, -0.05920351296663284, 0.42420727014541626, -0.7075801491737366, -0.5812562704086304, -0.45470523834228516, -0.49637383222579956, -0.4621729850769043, -0.08022484183311462, -0.3559366762638092, -0.30519863963127136, -0.12724801898002625, 0.3524470329284668, 0.24922972917556763, 0.05703858286142349, -0.34979748725891113, 0.4035033881664276, -0.09559239447116852, -0.17776204645633698, -0.15651503205299377, 0.6718531250953674, -0.4868294298648834, -0.7175531387329102, -0.8063515424728394, -0.13363081216812134, -0.05337003618478775, 0.06267954409122467, 0.12535007297992706, 0.2578200399875641, -0.01861094869673252, 0.5644108653068542, -0.32138484716415405, 0.3392837643623352, -0.3663631081581116, 0.09441062808036804, 0.05454929918050766, 0.5807402729988098, -0.22856265306472778, 0.6224995255470276, 0.5325628519058228, -0.22957591712474823, -0.1183055192232132, 0.5434378385543823, 0.7134807109832764, 0.20468737185001373, -0.17943346500396729, -0.08592969924211502, -0.057717617601156235, 0.0033776015043258667, 0.4518958330154419, 0.19884039461612701, -0.2617024779319763, 0.10595620423555374, -0.2965148687362671, 0.00487569160759449, -0.5370727777481079, -0.1666863113641739, -0.014921223744750023, 0.1848868578672409, -0.22062425315380096, -0.0874796062707901, -0.5835380554199219, 0.1840868890285492, -0.06613484025001526, -0.058504845947027206, -0.12279875576496124, 0.6655058860778809, -0.02822209894657135, -0.5245115756988525, 0.04849757254123688, -0.0417294055223465, -0.7508838772773743, 0.15119488537311554, -0.12835372984409332, 0.24179284274578094, -0.45698535442352295, 0.04473021253943443, -0.22299543023109436, 0.06664246320724487, -0.05260484293103218, -0.29584988951683044, -0.05002178996801376, 0.6333054304122925, 0.41433659195899963, 0.4375319480895996, -0.39384230971336365, -0.25190645456314087, 0.34896767139434814, -0.22275184094905853, -0.17298439145088196, 0.21253062784671783, 0.15736167132854462, -0.36713218688964844, 0.09845083951950073, 0.21736879646778107, -0.9029994606971741, -0.3776230812072754, -0.2527529001235962, -0.15691271424293518, -0.08362757414579391, 0.02444840595126152, 0.1808478832244873, -0.2001945823431015, -0.02859821729362011, -0.29489707946777344, -0.27978232502937317, -0.24736857414245605, 0.3176144063472748, 0.3716953992843628, -0.08464415371417999, 0.06381005048751831, 0.5033937692642212, -0.22597666084766388, 0.15349774062633514, 0.166713148355484, 0.24696727097034454, -0.6523793935775757, 0.43820178508758545, -0.2352529615163803, 1.0430347919464111, 0.09639517962932587, 0.14185041189193726, 0.08152782171964645, -0.3798058331012726, 0.0541277676820755, 0.3158506155014038, -0.10816602408885956, -0.08298633992671967, 0.0540834441781044, 0.08391769230365753, 0.45450785756111145, 0.13929633796215057, 0.8135476112365723, -0.6912750601768494, -0.08224894851446152, -0.12634426355361938, -0.3983262777328491, 0.23621046543121338, 0.041110657155

We can also see, which of the tokens have been concatenated from the `token` attribute.

If word-level embeddings are used with the option `method='all'` (return all the embeddings), then BertTagger creates an ambiguous layer, where words corresponding to multiple Bert tokens also have a separate embeddings annotation for each Bert token:

In [15]:
bert_tagger_word_all = BertTagger(method='all', bert_layers=[-3, -2, -1], 
                                  output_layer='bert_embeddings_word_all', token_level=False)
bert_tagger_word_all.tag(text)
text.bert_embeddings_word_all

Some weights of BertModel were not initialized from the model checkpoint at C:\Programmid\Miniconda3\envs\py312_devel\Lib\site-packages\estnltk\estnltk_resources\estbert\model_hf_tartunlp_2022-03-10\ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Layer(name='bert_embeddings_word_all', attributes=('token', 'bert_embedding'), spans=SL[Span('Aga', [{'token': 'aga', 'bert_embedding': <class 'list'>}]),
Span('mulle', [{'token': 'mulle', 'bert_embedding': <class 'list'>}]),
Span('tundub', [{'token': 'tundub', 'bert_embedding': <class 'list'>}]),
Span(',', [{'token': ',', 'bert_embedding': <class 'list'>}]),
Span('et', [{'token': 'et', 'bert_embedding': <class 'list'>}]),
Span('kogu', [{'token': 'kogu', 'bert_embedding': <class 'list'>}]),
Span('maailm', [{'token': 'maailm', 'bert_embedding': <class 'list'>}]),
Span('ootab', [{'token': 'ootab', 'bert_embedding': <class 'list'>}]),
Span('muusikamaailmalt', [{'token': 'muusika', 'bert_embedding': <class 'list'>}, {'token': '##maailma', 'bert_embedding': <class 'list'>}, {'token': '##lt', 'bert_embedding': <class 'list'>}]),
Span('midagi', [{'token': 'midagi', 'bert_embedding': <class 'list'>}]),
Span('erutavalt', [{'token': 'eru', 'bert_embedding': <class 'list'>}, {'token': '##tavalt', 'bert_embedding': <class 'list'>}]),
Span('uut', [{'token': 'uut', 'bert_embedding': <class 'list'>}]),
Span('minimalismi', [{'token': 'minima', 'bert_embedding': <class 'list'>}, {'token': '##lismi', 'bert_embedding': <class 'list'>}]),
Span('kõrvale', [{'token': 'korva', 'bert_embedding': <class 'list'>}, {'token': '##le', 'bert_embedding': <class 'list'>}]),
Span('.', [{'token': '.', 'bert_embedding': <class 'list'>}])])

## RobertaTagger

`esnltk_neural` also contains RobertaTagger, which allows to tag embeddings with the [Est-RoBERTa](https://huggingface.co/EMBEDDIA/est-roberta) model [(Ulčar & Robnik-Šikonja 2022)](https://link.springer.com/chapter/10.1007/978-3-031-16500-9_14).
The interface of RobertaTagger is analogous to that of BertTagger. 

The model required by RobertaTagger can be pre-downloaded via `snapshot_download`:

```python
from huggingface_hub import snapshot_download
snapshot_download('EMBEDDIA/est-roberta')
```

Alternatively, if you create a new instance of RobertaTagger and the model has not been downloaded yet, it'll be downloaded automatically.

Usage example:
```python
from estnltk import Text
from estnltk_neural.taggers import RobertaTagger
roberta_tagger = RobertaTagger()
# Create input text and add required layers
text = Text("Aga mulle tundub, et kogu maailm ootab muusikamaailmalt midagi erutavalt uut minimalismi kõrvale.")
text.tag_layer(['words', 'sentences'])
# Tag embeddings
roberta_tagger.tag(text)
# Browse results
text.roberta_embeddings
```