## <span style="color:purple">Morphological and Stanza analysis with MorphoSyntaxTagger</span>

The [estnltk_neural](https://github.com/estnltk/estnltk/tree/main/estnltk_neural) package contains `MorphoSyntaxTagger`, which provides VabamorfWithBertTagger's morphological analysis together with Stanza Syntax analysis.

## Prerequisites

*Note: you need to install [estnltk_neural](https://github.com/estnltk/estnltk/tree/main/estnltk_neural) package.*

Note that the Stanza model required by the tagger is not distributed with the estnltk\\_neural package.

MorphoSyntaxTagger uses:
- existing morph layer or VabamorfWithBertTagger (or other tagger for morph analysis layer)
- MorphExtendedTagger
- StanzaSyntaxTagger

For morph_analysis layer, either an existing layer name is provided with "morph_analysis_layer" parameter or the tagger is passes with "morph_analysis_tagger" parameter. There is no need to provide the tagger if morph_analysis layer already exists. If tagger is given, then a new morph_analsysi layer will be created regardless and "morph_analysis_layer" value will be overwritten with the morph_analysis_tagger's output_layer.

## Examples how to use MorphoSyntaxTagger

In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
from estnltk_neural.taggers import VabamorfWithBertTagger
from estnltk.taggers import MorphExtendedTagger
from estnltk_neural.taggers import StanzaSyntaxTagger
from estnltk_neural.taggers import MorphoSyntaxTagger
from estnltk import Text

### Usage without an existing morph_analysis layer

Requires:

- VabamorfWithBertTagger (or other tagger for morph analysis layer)
- MorphExtendedTagger
- StanzaSyntaxTagger

In [4]:
vwbt = VabamorfWithBertTagger(output_layer="morph_with_bert")

met = MorphExtendedTagger(output_layer="morph_extended", input_morph_analysis_layer="morph_with_bert")

depparse_path = "../stanza_treenimine/stanza1.14_ud2.18/model_morph_with_bert.pt"
sst = StanzaSyntaxTagger( output_layer="stanza_syntax", 
                                 input_type="morph_analysis",
                                 input_morph_layer="morph_with_bert",
                                 words_layer="words", 
                                 sentences_layer="sentences", 
                                 resources_path=None, 
                                 depparse_path =depparse_path, 
                                 add_parent_and_children=False, 
                                 use_gpu=False)

In [5]:
mst = MorphoSyntaxTagger(morph_analysis_tagger = vwbt,
                        morph_extended_tagger = met,
                         stanza_tagger = sst,
                         output_layer = "morphosyntax"
                        )

In [8]:
t3 = Text("""Kas sa tead ka, väike Rilli , et meil aias kasvab lilli? \
    Saal neid mitmesuguseid palistamas aiateid . \
    Koiduajal tõttan ma oma aeda vaatama . \
    Hommikul , kui kastan lilli , siis veel magad, väike Rilli . \
    Tule, Rilli, abiks mulle, tasuks kondi annan sulle !  \
    Lapsed aias tegutsevad , jalgteed puhtaks rehitsevad , siis veel kuldse liivaga kaetakse need hoolega . \
    Pärast puhata on ilus varjupikka põõsa vilus . \
    Ilmad kuumad , palavad , lilled aias näräbuvad. \
    Kastma pead neid hoolega , et nad võiksid kosuda . \
    Kui sul janu , aitab vesi . \
    Samuti ka lillekesi jooda igal hommikul , aega selleks küllalt sul . \
    Kaks lille ilusat on mul , toas kasvatasin endale , nüüd aga suve tulekul viin välja päiksepaistele . \
    Kaks lille ilusat on mul , need kingin varsti emale , ning sünnipäeva hommikul las teevad rõõmu temale . \
    Mesilane - linnukene lendab lillelt lillele , ise imetillukene , aga hoolas töödele. \
    Mesilane - linnukene mett sääl korjab sinule . \
    Mesi magus, lapsukene , maitseb igaühele ! \
    Palju lilli, palju päikest suve läbi meie aias rõõmustamas suurt ja väikest ; marju leiab suuke maias. \
    Tule meile, palun väga, aias tore mängida , tervitan sind lilledega kingin õuna magusa .""")

# create necessary layers before
t3.tag_layer(["words", "sentences"])

# morphosyntax tagging
mst.tag( t3 )

Text(text='Kas sa tead ka, väike Rilli , et meil aias kasvab lilli?     Saal neid mitmesuguseid palistamas aiateid .     Koiduajal tõttan ma oma aeda vaatama .     Hommikul , kui kastan lilli , siis veel magad, väike Rilli .     Tule, Rilli, abiks mulle, tasuks kondi annan sulle !      Lapsed aias tegutsevad , jalgteed puhtaks rehitsevad , siis veel kuldse liivaga kaetakse need hoolega .     Pärast puhata on ilus varjupikka põõsa vilus .     Ilmad kuumad , palavad , lilled aias näräbuvad.     Kastma pead neid hoolega , et nad võiksid kosuda .     Kui sul janu , aitab vesi .     Samuti ka lillekesi jooda igal hommikul , aega selleks küllalt sul .     Kaks lille ilusat on mul , toas kasvatasin endale , nüüd aga suve tulekul viin välja päiksepaistele .     Kaks lille ilusat on mul , need kingin varsti emale , ning sünnipäeva hommikul las teevad rõõmu temale .     Mesilane - linnukene lendab lillelt lillele , ise imetillukene , aga hoolas töödele.     Mesilane - linnukene mett sääl korjab sinule .     Mesi magus, lapsukene , maitseb igaühele !     Palju lilli, palju päikest suve läbi meie aias rõõmustamas suurt ja väikest ; marju leiab suuke maias.     Tule meile, palun väga, aias tore mängida , tervitan sind lilledega kingin õuna magusa .')

In [10]:
t3["sentences"][1].morphosyntax

Layer(name='morphosyntax', attributes=('id', 'lemma', 'root_tokens', 'clitic', 'xpostag', 'feats', 'extended_feats', 'head', 'deprel', 'stanza_pos', 'stanza_feats', 'stanza_lemma', 'parent_span', 'children'), spans=SL[Span('Saal', [{'id': 1, 'lemma': 'saal', 'root_tokens': ['saal'], 'clitic': '', 'xpostag': 'S', 'feats': 'sg n', 'extended_feats': 'com sg nom', 'head': 5, 'deprel': 'nsubj:cop', 'stanza_pos': 'S', 'stanza_feats': OrderedDict([('sg', 'sg'), ('n', 'n')]), 'stanza_lemma': 'saal', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('neid', [{'id': 2, 'lemma': 'see', 'root_tokens': ['see'], 'clitic': '', 'xpostag': 'P', 'feats': 'pl p', 'extended_feats': 'pl part', 'head': 3, 'deprel': 'det', 'stanza_pos': 'P', 'stanza_feats': OrderedDict([('pl', 'pl'), ('p', 'p')]), 'stanza_lemma': 'see', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('mitmesuguseid', [{'id': 3, 'lemma': 'mitmesugune', 'root_tokens': ['mitme', 'sugune'], 'clitic': '', 'xpostag': 'P', 'feats': 'pl p', 'extended_feats': 'pl part', 'head': 5, 'deprel': 'det', 'stanza_pos': 'P', 'stanza_feats': OrderedDict([('pl', 'pl'), ('p', 'p')]), 'stanza_lemma': 'mitmesugune', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('palistamas', [{'id': 4, 'lemma': 'palistama', 'root_tokens': ['palista'], 'clitic': '', 'xpostag': 'V', 'feats': 'mas', 'extended_feats': 'mod sup ps in', 'head': 5, 'deprel': 'xcomp', 'stanza_pos': 'V', 'stanza_feats': OrderedDict([('mas', 'mas')]), 'stanza_lemma': 'palistama', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('aiateid', [{'id': 5, 'lemma': 'aiatee', 'root_tokens': ['aia', 'tee'], 'clitic': '', 'xpostag': 'S', 'feats': 'pl p', 'extended_feats': 'com pl part', 'head': 0, 'deprel': 'root', 'stanza_pos': 'S', 'stanza_feats': OrderedDict([('pl', 'pl'), ('p', 'p')]), 'stanza_lemma': 'aiatee', 'parent_span': None, 'children': <class 'tuple'>}]),
Span('.', [{'id': 6, 'lemma': '.', 'root_tokens': ['.'], 'clitic': '', 'xpostag': 'Z', 'feats': '', 'extended_feats': '', 'head': 5, 'deprel': 'punct', 'stanza_pos': 'Z', 'stanza_feats': OrderedDict(), 'stanza_lemma': '.', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}])])

### Usage with an existing morph_analysis layer

Requires:

- morph_analysis layer
- MorphExtendedTagger
- StanzaSyntaxTagger

In [11]:
# still need the tagger to create the necessary layer beforehand
vwbt = VabamorfWithBertTagger(output_layer="morph_with_bert")

met = MorphExtendedTagger(output_layer="morph_extended", input_morph_analysis_layer="morph_with_bert")

depparse_path = "../stanza_treenimine/stanza1.14_ud2.18/model_morph_with_bert.pt"
sst = StanzaSyntaxTagger( output_layer="stanza_syntax", 
                                 input_type="morph_analysis",
                                 input_morph_layer="morph_with_bert",
                                 words_layer="words", 
                                 sentences_layer="sentences", 
                                 resources_path=None, 
                                 depparse_path =depparse_path, 
                                 add_parent_and_children=False, 
                                 use_gpu=False)

In [12]:
mst = MorphoSyntaxTagger(
                        morph_analysis_layer = "morph_with_bert",
                        morph_extended_tagger = met,
                         stanza_tagger = sst,
                         output_layer = "morphosyntax"
                        )

In [13]:
t3 = Text("""Kas sa tead ka, väike Rilli , et meil aias kasvab lilli? \
    Saal neid mitmesuguseid palistamas aiateid . \
    Koiduajal tõttan ma oma aeda vaatama . \
    Hommikul , kui kastan lilli , siis veel magad, väike Rilli . \
    Tule, Rilli, abiks mulle, tasuks kondi annan sulle !  \
    Lapsed aias tegutsevad , jalgteed puhtaks rehitsevad , siis veel kuldse liivaga kaetakse need hoolega . \
    Pärast puhata on ilus varjupikka põõsa vilus . \
    Ilmad kuumad , palavad , lilled aias näräbuvad. \
    Kastma pead neid hoolega , et nad võiksid kosuda . \
    Kui sul janu , aitab vesi . \
    Samuti ka lillekesi jooda igal hommikul , aega selleks küllalt sul . \
    Kaks lille ilusat on mul , toas kasvatasin endale , nüüd aga suve tulekul viin välja päiksepaistele . \
    Kaks lille ilusat on mul , need kingin varsti emale , ning sünnipäeva hommikul las teevad rõõmu temale . \
    Mesilane - linnukene lendab lillelt lillele , ise imetillukene , aga hoolas töödele. \
    Mesilane - linnukene mett sääl korjab sinule . \
    Mesi magus, lapsukene , maitseb igaühele ! \
    Palju lilli, palju päikest suve läbi meie aias rõõmustamas suurt ja väikest ; marju leiab suuke maias. \
    Tule meile, palun väga, aias tore mängida , tervitan sind lilledega kingin õuna magusa .""")


# create necessary layers before
t3.tag_layer(["words", "sentences"])
vwbt.tag( t3 )

# morphosyntax tagging
mst.tag( t3 )

Text(text='Kas sa tead ka, väike Rilli , et meil aias kasvab lilli?     Saal neid mitmesuguseid palistamas aiateid .     Koiduajal tõttan ma oma aeda vaatama .     Hommikul , kui kastan lilli , siis veel magad, väike Rilli .     Tule, Rilli, abiks mulle, tasuks kondi annan sulle !      Lapsed aias tegutsevad , jalgteed puhtaks rehitsevad , siis veel kuldse liivaga kaetakse need hoolega .     Pärast puhata on ilus varjupikka põõsa vilus .     Ilmad kuumad , palavad , lilled aias näräbuvad.     Kastma pead neid hoolega , et nad võiksid kosuda .     Kui sul janu , aitab vesi .     Samuti ka lillekesi jooda igal hommikul , aega selleks küllalt sul .     Kaks lille ilusat on mul , toas kasvatasin endale , nüüd aga suve tulekul viin välja päiksepaistele .     Kaks lille ilusat on mul , need kingin varsti emale , ning sünnipäeva hommikul las teevad rõõmu temale .     Mesilane - linnukene lendab lillelt lillele , ise imetillukene , aga hoolas töödele.     Mesilane - linnukene mett sääl korjab sinule .     Mesi magus, lapsukene , maitseb igaühele !     Palju lilli, palju päikest suve läbi meie aias rõõmustamas suurt ja väikest ; marju leiab suuke maias.     Tule meile, palun väga, aias tore mängida , tervitan sind lilledega kingin õuna magusa .')

In [15]:
t3["sentences"][1].morphosyntax

Layer(name='morphosyntax', attributes=('id', 'lemma', 'root_tokens', 'clitic', 'xpostag', 'feats', 'extended_feats', 'head', 'deprel', 'stanza_pos', 'stanza_feats', 'stanza_lemma', 'parent_span', 'children'), spans=SL[Span('Saal', [{'id': 1, 'lemma': 'saal', 'root_tokens': ['saal'], 'clitic': '', 'xpostag': 'S', 'feats': 'sg n', 'extended_feats': 'com sg nom', 'head': 5, 'deprel': 'nsubj:cop', 'stanza_pos': 'S', 'stanza_feats': OrderedDict([('sg', 'sg'), ('n', 'n')]), 'stanza_lemma': 'saal', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('neid', [{'id': 2, 'lemma': 'see', 'root_tokens': ['see'], 'clitic': '', 'xpostag': 'P', 'feats': 'pl p', 'extended_feats': 'pl part', 'head': 4, 'deprel': 'obj', 'stanza_pos': 'P', 'stanza_feats': OrderedDict([('pl', 'pl'), ('p', 'p')]), 'stanza_lemma': 'tema', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('mitmesuguseid', [{'id': 3, 'lemma': 'mitmesugune', 'root_tokens': ['mitme', 'sugune'], 'clitic': '', 'xpostag': 'P', 'feats': 'pl p', 'extended_feats': 'pl part', 'head': 5, 'deprel': 'det', 'stanza_pos': 'P', 'stanza_feats': OrderedDict([('pl', 'pl'), ('p', 'p')]), 'stanza_lemma': 'mitmesugune', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('palistamas', [{'id': 4, 'lemma': 'palistama', 'root_tokens': ['palista'], 'clitic': '', 'xpostag': 'V', 'feats': 'mas', 'extended_feats': 'mod sup ps in', 'head': 5, 'deprel': 'xcomp', 'stanza_pos': 'V', 'stanza_feats': OrderedDict([('mas', 'mas')]), 'stanza_lemma': 'palistama', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('aiateid', [{'id': 5, 'lemma': 'aiatee', 'root_tokens': ['aia', 'tee'], 'clitic': '', 'xpostag': 'S', 'feats': 'pl p', 'extended_feats': 'com pl part', 'head': 0, 'deprel': 'root', 'stanza_pos': 'S', 'stanza_feats': OrderedDict([('pl', 'pl'), ('p', 'p')]), 'stanza_lemma': 'aiatee', 'parent_span': None, 'children': <class 'tuple'>}]),
Span('.', [{'id': 6, 'lemma': '.', 'root_tokens': ['.'], 'clitic': '', 'xpostag': 'Z', 'feats': '', 'extended_feats': '', 'head': 5, 'deprel': 'punct', 'stanza_pos': 'Z', 'stanza_feats': OrderedDict(), 'stanza_lemma': '.', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}])])

In [16]:
# pre-existing morph_analysis layer remains
t3["sentences"][1].morph_with_bert

Layer(name='morph_with_bert', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Saal', [{'normalized_text': 'Saal', 'lemma': 'saal', 'root': 'saal', 'root_tokens': ['saal'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('neid', [{'normalized_text': 'neid', 'lemma': 'see', 'root': 'see', 'root_tokens': ['see'], 'ending': 'd', 'clitic': '', 'form': 'pl p', 'partofspeech': 'P'}, {'normalized_text': 'neid', 'lemma': 'tema', 'root': 'tema', 'root_tokens': ['tema'], 'ending': 'd', 'clitic': '', 'form': 'pl p', 'partofspeech': 'P'}]),
Span('mitmesuguseid', [{'normalized_text': 'mitmesuguseid', 'lemma': 'mitmesugune', 'root': 'mitme_sugune', 'root_tokens': ['mitme', 'sugune'], 'ending': 'id', 'clitic': '', 'form': 'pl p', 'partofspeech': 'P'}]),
Span('palistamas', [{'normalized_text': 'palistamas', 'lemma': 'palistama', 'root': 'palista', 'root_tokens': ['palista'], 'ending': 'mas', 'clitic': '', 'form': 'mas', 'partofspeech': 'V'}]),
Span('aiateid', [{'normalized_text': 'aiateid', 'lemma': 'aiatee', 'root': 'aia_tee', 'root_tokens': ['aia', 'tee'], 'ending': 'id', 'clitic': '', 'form': 'pl p', 'partofspeech': 'S'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])