## <span style="color:purple">Finding consistency errors with BasicConsistencyChecker</span>

The [estnltk_neural](https://github.com/estnltk/estnltk/tree/main/estnltk_neural) package contains `BasicConsistencyChecker`, which searches for basic consistency errors regarding deprels and feats.

## Prerequisites

*Note: you need to install [estnltk_neural](https://github.com/estnltk/estnltk/tree/main/estnltk_neural) package.*

Make sure that the correct feats extraction is selected in the '*_check_consistency*' function. The difference is that 'feats' is expected to be a dictionary and 'extended_feats' is a string where all feats are separated by a comma. Dictionary version is used in the older dataset layers and 'extended_feats' is intended for newer version in the future.

These examples are from the older dataset.

## Examples how to use BasicConsistencyChecker

The files used in this tutorial can be found also in the [test folder](https://github.com/estnltk/estnltk/tree/devel_1.7/estnltk_neural/estnltk_neural/tests/taggers/morphosyntax/test_files_basic_consistency).

In [2]:
from estnltk_neural.taggers import BasicConsistencyChecker
from estnltk import Text
from estnltk.converters import json_to_text, text_to_json
import os

In [3]:
tagger = BasicConsistencyChecker(
                        morphosyntax_layer = "v172_stanza_syntax",
                         output_layer="morphosyntax_consistency"
                        )

### Examples for all the rules in the tagger

In [4]:
# no errors, empty layer

s = json_to_text(file = "sentence_510950.json")

tagger.tag(s)
print(s.text)
s["morphosyntax_consistency"]

Kummati ei paistnud Julija treenerist isa näolt teatevahetuse hetkel mingit ärevust , pigem reibast enesekindlust .

Layer(name='morphosyntax_consistency', attributes=('id', 'lemma', 'root_tokens', 'clitic', 'xpostag', 'feats', 'extended_feats', 'head', 'deprel', 'error_type'), spans=SL[])

In [5]:
# nsubj but not 'nom'/'part'

s = json_to_text(file = "sentence_3.json")

tagger.tag(s)
print(s.text)
s["morphosyntax_consistency"]

Kaheksakümnendate aastate lõpus toimus Türi 1.

Layer(name='morphosyntax_consistency', attributes=('id', 'lemma', 'root_tokens', 'clitic', 'xpostag', 'feats', 'extended_feats', 'head', 'deprel', 'error_type'), spans=SL[Span('Türi', [{'id': 5, 'lemma': 'Türi', 'root_tokens': None, 'clitic': None, 'xpostag': 'S', 'feats': {'sg': 'sg', 'gen': 'gen', 'prop': 'prop'}, 'extended_feats': None, 'head': 4, 'deprel': 'nsubj', 'error_type': 'basic'}])])

In [6]:
# obj but not 'nom'/'part'/'gen'
# xcomp and feats is not empty

s = json_to_text(file = "sentence_5.json")

tagger.tag(s)
print(s.text)
s["morphosyntax_consistency"]

Bändi , mille solist ei osanud laulda , kidramees ei saanud keeltele pihta ja trummari eesmärk oli võimalikult palju müra teha .

Layer(name='morphosyntax_consistency', attributes=('id', 'lemma', 'root_tokens', 'clitic', 'xpostag', 'feats', 'extended_feats', 'head', 'deprel', 'error_type'), spans=SL[Span('Bändi', [{'id': 1, 'lemma': 'bänd', 'root_tokens': None, 'clitic': None, 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'adit': 'adit'}, 'extended_feats': None, 'head': 11, 'deprel': 'obj', 'error_type': 'basic'}]),
Span('laulda', [{'id': 7, 'lemma': 'laulma', 'root_tokens': None, 'clitic': None, 'xpostag': 'V', 'feats': {'aux': 'aux', 'inf': 'inf'}, 'extended_feats': None, 'head': 6, 'deprel': 'xcomp', 'error_type': 'basic'}])])

In [7]:
# advcl and feats is not empty

s = json_to_text(file = "sentence_16.json")

tagger.tag(s)
print(s.text)
s["morphosyntax_consistency"]

Hakkasin koos venna Suleviga muusikat tegema , kui tema oli viie- ja mina seitsmeaastane .

Layer(name='morphosyntax_consistency', attributes=('id', 'lemma', 'root_tokens', 'clitic', 'xpostag', 'feats', 'extended_feats', 'head', 'deprel', 'error_type'), spans=SL[Span('tegema', [{'id': 6, 'lemma': 'tegema', 'root_tokens': None, 'clitic': None, 'xpostag': 'V', 'feats': {'ps': 'ps', 'ill': 'ill', 'mod': 'mod', 'sup': 'sup'}, 'extended_feats': None, 'head': 1, 'deprel': 'xcomp', 'error_type': 'basic'}]),
Span('viie-', [{'id': 11, 'lemma': 'viis', 'root_tokens': None, 'clitic': None, 'xpostag': 'N', 'feats': {'l': 'l', 'sg': 'sg', 'gen': 'gen', 'card': 'card'}, 'extended_feats': None, 'head': 1, 'deprel': 'advcl', 'error_type': 'basic'}])])

In [8]:
# advmod and feats is not empty

s = json_to_text(file = "sentence_21424517.json")

tagger.tag(s)
print(s.text)
s["morphosyntax_consistency"]

devilgirl_unes: ulluke aga nyyd tulid sina ja enem ma ei pea siin igavlema =))) ja siis sellega vaidlema

Layer(name='morphosyntax_consistency', attributes=('id', 'lemma', 'root_tokens', 'clitic', 'xpostag', 'feats', 'extended_feats', 'head', 'deprel', 'error_type'), spans=SL[Span('aga', [{'id': 4, 'lemma': 'aga', 'root_tokens': None, 'clitic': None, 'xpostag': 'J', 'feats': {'crd': 'crd', 'sub': 'sub'}, 'extended_feats': None, 'head': 6, 'deprel': 'advmod', 'error_type': 'basic'}])])

In [9]:
# nsubj:cop but not 'nom'/'part'

s = json_to_text(file = "sentence_209696.json")

tagger.tag(s)
print(s.text)
s["morphosyntax_consistency"]

Teine kasutatav tunnus oli kolmeväärtuseline ning lisaks eelnimetatutele oli siin ka kategooria " üks vanematest on surnud " .

Layer(name='morphosyntax_consistency', attributes=('id', 'lemma', 'root_tokens', 'clitic', 'xpostag', 'feats', 'extended_feats', 'head', 'deprel', 'error_type'), spans=SL[Span('kategooria', [{'id': 12, 'lemma': 'kategooria', 'root_tokens': None, 'clitic': None, 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'gen': 'gen'}, 'extended_feats': None, 'head': 17, 'deprel': 'nsubj:cop', 'error_type': 'basic'}])])

In [10]:
# obl and 'nom' in feats

s = json_to_text(file = "sentence_84.json")

tagger.tag(s)
print(s.text)
s["morphosyntax_consistency"]

Mõned tüdrukud muutusid lausa tüütuks , uurisid telefoninumbri välja ja helistasid iga päev hommikust õhtuni .

Layer(name='morphosyntax_consistency', attributes=('id', 'lemma', 'root_tokens', 'clitic', 'xpostag', 'feats', 'extended_feats', 'head', 'deprel', 'error_type'), spans=SL[Span('tüütuks', [{'id': 5, 'lemma': 'tüütu', 'root_tokens': None, 'clitic': None, 'xpostag': 'A', 'feats': {'sg': 'sg', 'tr': 'tr', 'pos': 'pos'}, 'extended_feats': None, 'head': 3, 'deprel': 'xcomp', 'error_type': 'basic'}]),
Span('päev', [{'id': 13, 'lemma': 'päev', 'root_tokens': None, 'clitic': None, 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'nom': 'nom'}, 'extended_feats': None, 'head': 11, 'deprel': 'obl', 'error_type': 'basic'}])])